"""
My First Dispatch Model (MFDM)
==============================

A least-cost economic dispatch model built with PuLP.

Sets
    PLANTS  power plants
    HOURS   hour-by-hour time steps
    FUELS   fuels

Parameters
    availability[p][t]  MW that plant p can supply in hour t. Thermal plants
                        are available at nameplate around the clock; wind and
                        solar are nameplate scaled by an hourly capacity
                        factor read from profiles.csv.
    marginal_cost[p]    fuel_price / efficiency + VOM   ($/MWh)
    ramp_rate[p]        MW the plant may move between adjacent hours
    ramp_cost[p]        premium per MWh moved, see "Ramping" below  ($/MWh)
    demand[t]           MWh required in hour t

Decision variables
    gen[p][t]           MWh generated by plant p in hour t
    unserved[t]         MWh of demand left unmet in hour t
    spill[t]            MWh generated in hour t that had to be thrown away
    ramp_up[p][t]       MWh of upward movement by plant p into hour t
    ramp_down[p][t]     MWh of downward movement by plant p into hour t

Objective
    minimise sum over p, t of marginal_cost[p] * gen[p][t]
           + sum over t of VOLL * unserved[t]
           + sum over t of SPILL_COST * spill[t]
           + sum over p, t of ramp_cost[p] * (ramp_up[p][t] + ramp_down[p][t])

Constraints
    energy balance  sum over p of gen[p][t] + unserved[t] - spill[t] == demand[t]
    capacity        gen[p][t] <= availability[p][t]
    ramp up         gen[p][t] - gen[p][t-1] <= ramp_up[p][t]
    ramp down       gen[p][t-1] - gen[p][t] <= ramp_down[p][t] + forced_down[p][t]
    ramp rate       ramp_up[p][t], ramp_down[p][t] <= ramp_rate[p]

Scarcity
    Demand that no plant can cover is not an error, it is expensive. The
    `unserved` variable lets the balance always be met, priced at VOLL (the
    value of lost load), which sits far above every plant's marginal cost so
    the solver only reaches for it once all real capacity is exhausted. The
    consequence is that the energy balance can no longer be infeasible, so a
    non-optimal solver status now means a bug in the model rather than a
    problem with the data.
Ramping
    A plant cannot jump to any output it likes from one hour to the next. Two
    things now limit it, and they pull in different directions.

    A ramp *rate* is a hard limit: `ramp_rate[p]` MW of movement per hour, in
    either direction, read straight from plants.csv. A ramp *cost* is a price
    on movement: burning fuel while changing output is less efficient than
    burning it at a steady state, so plants.csv carries a second, worse
    efficiency for the ramping case, and the premium is the difference between
    the two fuel costs,

        ramp_cost[p] = fuel_price[p] / ramp_efficiency[p]
                     - fuel_price[p] / efficiency[p]

    charged on every MWh moved. A ramped MWh is therefore charged twice: once
    at the plant's ordinary marginal cost through the `marginal_cost * gen`
    term, and again for the premium. That is what "the extra cost of a ramped
    MWh over a normal one" means.

    Hour 1 has no predecessor, so every plant starts wherever it likes free of
    charge, and the horizon does not wrap.

Spill
    A ramp *down* limit puts a floor under a plant rather than a ceiling over
    it, and a floor can force the fleet to generate more than the demand. The
    `unserved` variable only covers the opposite direction, so without a way
    to shed the surplus the model would have to hold demand artificially high.
    `spill[t]` is that way: energy that was generated and had to be thrown
    away.

    Spill is priced at SPILL_COST, deliberately *not* at VOLL. See the comment
    on the constant for why the two must differ.

    Spill is the mirror of unserved energy and should not be confused with
    Curtailment, which is renewable resource that was available and simply not
    taken. Curtailment is free and implicit; spill is priced and explicit. See
    CONTEXT.md.

Prices
    Ramping makes the objective intertemporal, and that changes what a price
    is. An extra MWh in hour t now also changes what it costs to serve t-1 and
    t+1, so the marginal cost of serving load stops being equal to any single
    plant's marginal cost.

    The model therefore reports the *dual* of the energy balance as the
    clearing price. It is the honest answer to "what would one more MWh in
    this hour cost the system", which is what a price is for.

    The old merit-order calculation survives as a diagnostic under the name
    "Highest Running Cost", which is what it always measured: who was last in
    the stack. It is not a price and must not be used as one.

    A spill hour prices *negative*: one more MWh of demand would save a MWh
    from being destroyed. This falls out of the dual without a special case.

Reads the four CSVs in inputs/ and writes dispatch_results.csv and
plant_summary.csv into results/. Run dashboard/dashboard.py afterwards to
explore the results interactively.

Array layout
    Hourly quantities are held as numpy arrays of shape (n_plants, n_hours),
    with rows ordered by PLANTS and columns ordered by HOURS. The parameter
    dictionary carries `avail` (availability), `mc_vec` (marginal cost, one
    per plant), `ramp_rate_vec`, `ramp_cost_vec`, `demand_vec` and
    `profiled_mask` in this form. The older dict-of-dicts views
    (`availability`, `marginal_cost`, `demand`) are kept alongside them
    because the reporting code reads more clearly with named lookups; they are
    derived from the arrays so the two cannot drift apart.
"""

from pathlib import Path
import argparse
import sys
import time

import numpy as np
import pandas as pd
import pulp

# runstore lives in run_archive/, which is a sibling folder rather than a
# package, so it has to be put on the import path before importing it.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "run_archive"))
import runstore


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent          # model/
REPO_ROOT = BASE_DIR.parent

# Inputs are read from inputs/ and results are written to results/, both at
# the repo root, so the model folder holds only code.
INPUTS_DIR = REPO_ROOT / "inputs"
RESULTS_DIR = REPO_ROOT / "results"

PLANTS_FILE = INPUTS_DIR / "plants.csv"
FUEL_FILE = INPUTS_DIR / "fuel.csv"
DEMAND_FILE = INPUTS_DIR / "demand.csv"
PROFILE_FILE = INPUTS_DIR / "profiles.csv"


# Generation below this is treated as "not running" when finding the marginal
# plant, so that solver round-off does not set the price.
TOL = 1e-6

# Value of Lost Load: what an hour of unmet demand is worth to the people who
# go without. Demand the fleet cannot cover is priced at this rather than
# making the model infeasible. 8300 $/MWh is the low end of the European
# Commission JRC estimate for Greece; see docs/research/scarcity_pricing.md.
# It must stay well above the most expensive plant's marginal cost, otherwise
# the solver would rather shed load than run that plant.
VOLL = 8300.0

# What a MWh of spilled energy costs: energy that was generated because a
# plant could not ramp down fast enough, and then had to be thrown away.
#
# This must NOT be set to VOLL, even though spill is the mirror of unserved
# energy, because the two are not symmetric in cost. Shedding a MWh *removes*
# a MWh of generation, so it saves VOLL minus the plant's marginal cost.
# Dumping a MWh *requires* a MWh of extra generation, so it costs SPILL_COST
# plus that marginal cost. Set the two constants equal and shedding always
# comes out cheaper by twice the marginal cost, so the solver blacks out real
# demand rather than dump a surplus, and `spill` never leaves zero.
#
# 1000 $/MWh sits far above the most expensive plant's marginal cost, so spill
# stays firmly last in the stack and is never used as a cheap way to dodge
# generating, while staying far enough below VOLL that dumping surplus is
# always preferred to shedding load. It is a modelling constant chosen for
# those two properties, not a physical quantity, and is worth revisiting.
SPILL_COST = 1000.0

# Technologies whose output is limited by an hourly resource profile rather
# than being available at nameplate around the clock. The value is the token
# looked for in the profiles.csv column headers.
PROFILE_TECHNOLOGIES = {
    "Wind": "wind",
    "Solar": "solar",
}


# --------------------------------------------------------------------------
# Step 1 - load data
# --------------------------------------------------------------------------

def load_data():
    """Read the four input CSVs and return them as DataFrames."""
    for path in (PLANTS_FILE, FUEL_FILE, DEMAND_FILE, PROFILE_FILE):
        if not path.exists():
            raise FileNotFoundError("Could not find input file: {}".format(path))

    # keep_default_na=False so that Solar's fuel of "None" stays the literal
    # string "None" rather than becoming NaN.
    plants = pd.read_csv(PLANTS_FILE, keep_default_na=False)
    fuel = pd.read_csv(FUEL_FILE)
    demand = pd.read_csv(DEMAND_FILE)

    # profiles.csv has two header rows: a region row (",FRA,FRA") and a
    # series row ("hours,wind (won),solar (solEB)"). Read both, then flatten
    # to single names of the form "FRA wind (won)", keeping the region so
    # multi-region files stay unambiguous.
    profile = pd.read_csv(PROFILE_FILE, header=[0, 1])
    flat = []
    for region, series in profile.columns:
        region = "" if str(region).startswith("Unnamed") else str(region).strip()
        series = str(series).strip()
        flat.append("{} {}".format(region, series).strip())
    profile.columns = flat

    # Tidy up stray whitespace in the text columns.
    for df in (plants, fuel, demand):
        df.columns = [c.strip() for c in df.columns]
    for col in ("Plant", "Technology", "Fuel"):
        plants[col] = plants[col].astype(str).str.strip()
    fuel["Technology"] = fuel["Technology"].astype(str).str.strip()

    return plants, fuel, demand, profile


# --------------------------------------------------------------------------
# Steps 2 and 3 - sets and parameters
# --------------------------------------------------------------------------

def build_parameters(plants, fuel, demand, profile):
    """Turn the raw DataFrames into the sets and parameter dictionaries."""

    # --- sets ---
    PLANTS = list(plants["Plant"])
    HOURS = [int(h) for h in demand["Hour"]]
    check_hours(HOURS)

    # --- fuel prices ---
    #Anything not listed is free.
    fuel_price = dict(zip(fuel["Technology"], fuel["Fuel Price ($/MWhTh)"].astype(float)))

    def price_of(fuel_name):
        if fuel_name is None:
            return 0.0
        if str(fuel_name).strip().lower() in ("none", "nan", ""):
            return 0.0
        if fuel_name not in fuel_price:
            print("  note: no fuel price listed for '{}', treating as $0/MWhTh".format(fuel_name))
            return 0.0
        return fuel_price[fuel_name]

    # --- per plant parameters ---
    capacity = {}
    efficiency = {}
    vom = {}
    technology = {}
    plant_fuel = {}
    marginal_cost = {}
    ramp_rate = {}
    ramp_efficiency = {}
    ramp_cost = {}

    # Located by prefix rather than by exact header, because the ramping
    # efficiency column is currently mislabelled "Ramp_efficiency($/hr)" while
    # holding efficiencies in MWh/MWhTh. Matching on the prefix means renaming
    # it to "Ramp_efficiency (MWh/MWhTh)" does not break the model.
    rate_col = find_column(plants, "Ramp_rate", "plants.csv")
    ramp_eff_col = find_column(plants, "Ramp_efficiency", "plants.csv")

    for _, row in plants.iterrows():
        p = row["Plant"]
        capacity[p] = float(row["Capacity (MW)"])
        efficiency[p] = float(row["Efficiency (MWh/MWhTh)"])
        vom[p] = float(row["VOM ($/MWh)"])
        technology[p] = row["Technology"]
        plant_fuel[p] = row["Fuel"]
        ramp_rate[p] = float(row[rate_col])
        ramp_efficiency[p] = float(row[ramp_eff_col])

        if efficiency[p] <= 0:
            raise ValueError("Plant {} has a non-positive efficiency".format(p))
        if ramp_efficiency[p] <= 0:
            raise ValueError(
                "Plant {} has a non-positive ramping efficiency".format(p))

        # A plant burns fuel less efficiently while it is moving than while it
        # is holding steady, so its ramping efficiency cannot be the better of
        # the two. If it were, the premium below would come out negative and
        # the solver would be paid to jiggle the plant up and down.
        if ramp_efficiency[p] > efficiency[p] + TOL:
            raise ValueError(
                "Plant {} has a ramping efficiency ({:.4f}) better than its "
                "ordinary efficiency ({:.4f}). Ramping is less efficient than "
                "steady running, not more, so this would make the ramp premium "
                "negative and pay the solver to move the plant about."
                .format(p, ramp_efficiency[p], efficiency[p]))
        if ramp_rate[p] < 0:
            raise ValueError("Plant {} has a negative ramp rate".format(p))

        # marginal cost = fuel cost / efficiency + VOM
        marginal_cost[p] = price_of(row["Fuel"]) / efficiency[p] + vom[p]

        # Ramp premium: what a moved MWh costs *over and above* a steady one.
        # VOM is not in here because it is charged on every MWh either way,
        # through marginal_cost; only the fuel burn differs while ramping.
        ramp_cost[p] = (price_of(row["Fuel"]) / ramp_efficiency[p]
                        - price_of(row["Fuel"]) / efficiency[p])

    # --- availability: nameplate capacity, scaled by an hourly resource
    # profile for the technologies that have one ---
    #
    # Built as a single (n_plants, n_hours) array. Rows for plants without a
    # profile stay at a factor of 1.0, i.e. available at nameplate around the
    # clock. The dict-of-dicts view is derived from the array below.
    profile_factors = build_profile_factors(profile, technology, HOURS)

    cap_vec = np.array([capacity[p] for p in PLANTS], dtype=float)
    mc_vec = np.array([marginal_cost[p] for p in PLANTS], dtype=float)
    profiled_mask = np.array([p in profile_factors for p in PLANTS], dtype=bool)

    factors_matrix = np.ones((len(PLANTS), len(HOURS)), dtype=float)
    for i, p in enumerate(PLANTS):
        factors = profile_factors.get(p)
        if factors is not None:
            factors_matrix[i] = [factors[t] for t in HOURS]

    avail = cap_vec[:, None] * factors_matrix

    ramp_rate_vec = np.array([ramp_rate[p] for p in PLANTS], dtype=float)
    ramp_cost_vec = np.array([ramp_cost[p] for p in PLANTS], dtype=float)

    # How much a plant is allowed to ramp down *beyond* its rate limit without
    # being charged, because its own resource collapsed underneath it.
    #
    # Without this a profiled plant is trapped by its own good hours. The
    # ramp-down limit puts a floor under a plant, gen[t] >= gen[t-1] - rate,
    # while the capacity constraint puts a ceiling over it, gen[t] <= avail[t].
    # When a wind or solar profile falls faster than the plant's ramp rate,
    # those two cannot both be satisfied at any positive output, so the only
    # way to obey them is to have been generating far below the resource in
    # the earlier hour.
    #
    # This is not infeasibility. The all-zeros dispatch always satisfies every
    # ramp constraint, so the LP can always retreat to it and price the demand
    # at VOLL. That is exactly the problem: the failure is silent and shows up
    # as an absurdly expensive answer rather than an error. Measured on a
    # fixture with a 500 MW solar farm limited to 10 MW/hr and a resource that
    # falls to zero after one hour, removing this allowance takes the
    # objective from $4,400 to $2,415,010 and leaves 58% of demand unserved,
    # because the plant may only use 10 MWh of its 500 MWh peak.
    #
    # Column 0 is zero because hour 1 has no predecessor and carries no ramp
    # constraint. Elsewhere the allowance is exactly the drop in availability,
    # so a plant is never penalised for a ramp down that the weather forced on
    # it, and never has to hold back in a good hour to protect itself.
    #
    # On the current inputs this never binds, because wind and solar both have
    # a ramp rate equal to their nameplate capacity. It exists so that editing
    # one number in plants.csv cannot silently wreck the dispatch.
    forced_down = np.zeros_like(avail)
    forced_down[:, 1:] = np.maximum(0.0, avail[:, :-1] - avail[:, 1:])

    # Legacy dict-of-dicts view, derived from `avail` so the two agree by
    # construction.
    availability = {p: dict(zip(HOURS, avail[i]))
                    for i, p in enumerate(PLANTS)}

    # --- demand ---
    demand_col = [c for c in demand.columns if c.lower().startswith("demand")][0]
    demand_vec = demand[demand_col].astype(float).to_numpy()
    demand_by_hour = dict(zip(HOURS, demand_vec))

    return {
        "PLANTS": PLANTS,
        "HOURS": HOURS,
        "capacity": capacity,
        "efficiency": efficiency,
        "vom": vom,
        "technology": technology,
        "plant_fuel": plant_fuel,
        "marginal_cost": marginal_cost,
        "ramp_rate": ramp_rate,
        "ramp_efficiency": ramp_efficiency,
        "ramp_cost": ramp_cost,
        "availability": availability,
        "profiled": set(profile_factors),
        "demand": demand_by_hour,
        # Array views, see "Array layout" in the module docstring.
        "avail": avail,
        "cap_vec": cap_vec,
        "mc_vec": mc_vec,
        "ramp_rate_vec": ramp_rate_vec,
        "ramp_cost_vec": ramp_cost_vec,
        "forced_down": forced_down,
        "demand_vec": demand_vec,
        "profiled_mask": profiled_mask,
    }


def find_column(df, prefix, filename):
    """Locate the one column of `df` whose name starts with `prefix`."""
    matches = [c for c in df.columns if c.strip().lower().startswith(prefix.lower())]
    if not matches:
        raise ValueError(
            "{} has no column starting with '{}'. Columns present: {}"
            .format(filename, prefix, ", ".join(df.columns)))
    if len(matches) > 1:
        raise ValueError(
            "{} has more than one column starting with '{}': {}. "
            "Column names must be unambiguous.".format(filename, prefix, matches))
    return matches[0]


def check_hours(HOURS):
    """Assert that HOURS is ascending, contiguous and free of duplicates.

    The hours are taken straight from the row order of demand.csv, which was
    harmless while every hour stood alone. The ramp constraints link each hour
    to the one before it in this list, so a gap, a duplicate or a stray sort
    order would quietly constrain the wrong pair of hours and the model would
    still solve, just against a horizon nobody intended.
    """
    if len(HOURS) < 1:
        raise ValueError("demand.csv contains no hours.")

    duplicates = sorted(set(h for h in HOURS if HOURS.count(h) > 1))
    if duplicates:
        raise ValueError(
            "demand.csv repeats {} hour(s), first {}. Each hour must appear "
            "once.".format(len(duplicates), duplicates[0]))

    breaks = [(HOURS[i - 1], HOURS[i]) for i in range(1, len(HOURS))
              if HOURS[i] != HOURS[i - 1] + 1]
    if breaks:
        a, b = breaks[0]
        raise ValueError(
            "demand.csv hours must be ascending and contiguous, but hour {} is "
            "followed by hour {} ({} such break(s) in total). Ramping links "
            "each hour to the previous row, so the horizon cannot have gaps or "
            "be out of order.".format(a, b, len(breaks)))


def build_profile_factors(profile, technology, HOURS):
    """Map each profiled plant to its hourly capacity factor.

    Returns {plant: {hour: factor}} containing only the plants whose
    technology has a matching column in profiles.csv. Plants absent from the
    result are treated as available at nameplate in every hour.
    """
    hour_col = profile.columns[0]
    available_hours = set(int(h) for h in profile[hour_col])

    missing = [t for t in HOURS if t not in available_hours]
    if missing:
        raise ValueError(
            "profiles.csv is missing {} of the {} hours in demand.csv "
            "(first missing: hour {}).".format(len(missing), len(HOURS), missing[0]))

    # Restrict profileto the modelled hours
    idx = profile[hour_col].astype(int)
    sub = profile.set_index(idx).loc[HOURS]

    factors = {}
    for plant, tech in technology.items():
        token = PROFILE_TECHNOLOGIES.get(tech)
        if token is None:
            continue

        matches = [c for c in profile.columns
                   if c is not hour_col and token in c.lower()]
        if not matches:
            print("  note: technology '{}' has no profile column in profiles.csv, "
                  "treating {} as always available".format(tech, plant))
            continue
        if len(matches) > 1:
            raise ValueError(
                "Technology '{}' matches more than one profile column: {}. "
                "Column names must be unambiguous.".format(tech, matches))

        series = sub[matches[0]].astype(float)
        lo, hi = float(series.min()), float(series.max())
        if lo < -TOL or hi > 1.0 + TOL:
            raise ValueError(
                "Profile column '{}' has values outside 0 to 1 (min {:.4f}, "
                "max {:.4f}). Expected capacity factors.".format(matches[0], lo, hi))

        factors[plant] = {t: float(v) for t, v in zip(HOURS, series.values)}

    return factors


def check_demand(par):
    "Flag suspicious demand values"
    zeros = [t for t in par["HOURS"] if par["demand"][t] <= 0.0]
    if zeros:
        shown = ", ".join(str(t) for t in zeros[:10])
        more = " and {} more".format(len(zeros) - 10) if len(zeros) > 10 else ""
        print("  WARNING: demand is zero or negative in {} hour(s): {}{}."
              .format(len(zeros), shown, more))
        print("           Check demand.csv. The model will dispatch nothing "
              "in those hours.\n")


def check_capacity_adequacy(par):
    "Warn before solving if demand exceeds everything the fleet can offer"
    short = []
    for t in par["HOURS"]:
        total = sum(par["availability"][p][t] for p in par["PLANTS"])
        if total < par["demand"][t] - TOL:
            short.append((t, par["demand"][t], total))

    if short:
        t, d, a = short[0]
        worst = max(short, key=lambda r: r[1] - r[2])
        print("  WARNING: demand exceeds available capacity in {} of {} hour(s)."
              .format(len(short), len(par["HOURS"])))
        print("           First is hour {}: demand {:,.2f} MWh vs {:,.2f} MW available."
              .format(t, d, a))
        print("           Worst is hour {}, short by {:,.2f} MW."
              .format(worst[0], worst[1] - worst[2]))
        print("           The shortfall will be priced at ${:,.2f}/MWh (VoLL). "
              "Check plants.csv and demand.csv.\n".format(VOLL))

# --------------------------------------------------------------------------
# Steps 4 to 7 - build and solve the LP
# --------------------------------------------------------------------------

def build_and_solve(par):
    "Build the dispatch LP, solve it, and return the model and variables."

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]

    # Every hour but the first has a predecessor, and so a ramp constraint.
    # Hour 1 is where the fleet starts from nothing, free of charge.
    RAMP_HOURS = HOURS[1:]
    previous = {t: HOURS[i] for i, t in enumerate(HOURS[1:])}

    prob = pulp.LpProblem("Economic_Dispatch", pulp.LpMinimize)

    # --- Step 4: decision variables ---
    gen = pulp.LpVariable.dicts("gen", (PLANTS, HOURS), lowBound=0, cat="Continuous")

    # Unmet demand, one per hour. See "Scarcity" in the module docstring.
    unserved = pulp.LpVariable.dicts("unserved", HOURS, lowBound=0, cat="Continuous")

    # Surplus that had to be thrown away. See "Spill" in the module docstring.
    spill = pulp.LpVariable.dicts("spill", HOURS, lowBound=0, cat="Continuous")

    # Movement between adjacent hours, split into two non-negative variables
    # so that the absolute size of the move can be priced linearly. The upper
    # bound is the hard ramp rate limit, which is why no separate constraint
    # is needed for it.
    ramp_up = {p: {t: pulp.LpVariable(
        "rampup_{}_{}".format(p.replace(" ", "_"), t),
        lowBound=0, upBound=par["ramp_rate"][p]) for t in RAMP_HOURS} for p in PLANTS}
    ramp_down = {p: {t: pulp.LpVariable(
        "rampdown_{}_{}".format(p.replace(" ", "_"), t),
        lowBound=0, upBound=par["ramp_rate"][p]) for t in RAMP_HOURS} for p in PLANTS}

    # Cost-free headroom on the ramp-down limit, fixed by the collapse in the
    # plant's own availability. See `forced_down` in build_parameters.
    forced_down = {p: dict(zip(HOURS, par["forced_down"][i]))
                   for i, p in enumerate(PLANTS)}

    # --- Step 5: objective, total production cost, plus the cost of any
    # demand left unserved, any energy thrown away, and any movement ---
    prob += (
        pulp.lpSum(par["marginal_cost"][p] * gen[p][t] for p in PLANTS for t in HOURS)
        + pulp.lpSum(VOLL * unserved[t] for t in HOURS)
        + pulp.lpSum(SPILL_COST * spill[t] for t in HOURS)
        + pulp.lpSum(par["ramp_cost"][p] * (ramp_up[p][t] + ramp_down[p][t])
                     for p in PLANTS for t in RAMP_HOURS),
        "Total_Production_Cost",
    )

    # --- Step 6a: energy balance, one per hour ---
    # Named so the dual (shadow price) can be pulled out after solving. Spill
    # enters negatively: it is generation that did not serve demand.
    for t in HOURS:
        prob += (
            pulp.lpSum(gen[p][t] for p in PLANTS) + unserved[t] - spill[t]
            == par["demand"][t],
            "balance_{}".format(t),
        )

    # --- Step 6b: capacity, one per plant per hour ---
    for p in PLANTS:
        for t in HOURS:
            prob += (
                gen[p][t] <= par["availability"][p][t],
                "cap_{}_{}".format(p.replace(" ", "_"), t),
            )

    # --- Step 6c: ramping, one pair per plant per hour after the first ---
    # These are inequalities, so ramp_up and ramp_down are only pushed down to
    # the true movement by their cost in the objective. A plant with a zero
    # ramp premium leaves them free to sit anywhere up to the rate limit,
    # which is why the reported ramp quantities are recomputed from the
    # generation profile after solving rather than read from these variables.
    for p in PLANTS:
        for t in RAMP_HOURS:
            prev = previous[t]
            prob += (
                gen[p][t] - gen[p][prev] <= ramp_up[p][t],
                "rampup_{}_{}".format(p.replace(" ", "_"), t),
            )
            prob += (
                gen[p][prev] - gen[p][t] <= ramp_down[p][t] + forced_down[p][t],
                "rampdown_{}_{}".format(p.replace(" ", "_"), t),
            )

    # --- Step 7: solve ---
    n_vars = (len(PLANTS) * len(HOURS)          # gen
              + 2 * len(HOURS)                   # unserved, spill
              + 2 * len(PLANTS) * len(RAMP_HOURS))  # ramp up and down
    print("Solving: {} variables, {} constraints ...".format(
        n_vars, len(prob.constraints)))
    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    status = pulp.LpStatus[prob.status]
    if status != "Optimal":
        raise RuntimeError(
            "Solver did not reach an optimal solution (status: {}). "
            "The all-zeros dispatch always satisfies every constraint in this "
            "model - unserved demand is priced at VoLL rather than forbidden, "
            "surplus can be spilled, and no plant has a lower bound above zero "
            "- so a feasible point always exists and this is a bug in how the "
            "LP is built rather than a problem with the input data."
            .format(status)
        )
    print("Solver status: {}\n".format(status))

    return prob, gen, unserved, spill


# --------------------------------------------------------------------------
# Step 8 - results and clearing price
# --------------------------------------------------------------------------

def build_results(par, prob, gen, unserved, spill):
    """Assemble the hourly results table, including the clearing price."""

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]
    avail, mc_vec, demand_vec = par["avail"], par["mc_vec"], par["demand_vec"]

    # Pull the solution out of the solver once, into a (n_plants, n_hours)
    # array laid out the same way as `avail`. Everything below is then plain
    # array arithmetic. `or 0.0` guards against a None from an unused
    # variable.
    output = np.array(
        [[gen[p][t].value() or 0.0 for t in HOURS] for p in PLANTS],
        dtype=float)

    unserved_vec = np.array([unserved[t].value() or 0.0 for t in HOURS], dtype=float)
    spill_vec = np.array([spill[t].value() or 0.0 for t in HOURS], dtype=float)

    # Ramp quantities, recomputed from the generation profile rather than read
    # from the LP's ramp variables. Those variables are bounded below by the
    # true movement but not pinned to it, so a plant with a zero ramp premium
    # can leave them anywhere up to its rate limit without changing the
    # objective. The generation profile is the only honest source. Column 0 is
    # zero: hour 1 has no predecessor, so nothing moved into it.
    delta = np.zeros_like(output)
    delta[:, 1:] = output[:, 1:] - output[:, :-1]
    ramp_up_arr = np.maximum(0.0, delta)
    ramp_down_arr = np.maximum(0.0, -delta)

    # The premium alone, not the cost of the ramped energy. The fuel and VOM
    # underneath a ramped MWh are already counted in Production Cost, so
    # adding them here would double count against the LP objective.
    ramp_cost_vec = par["ramp_cost_vec"]
    ramp_cost_hourly = ramp_cost_vec @ (ramp_up_arr + ramp_down_arr)

    # Clearing price: the dual of the energy balance, which is what one more
    # MWh in this hour would cost the system. With ramping in the objective
    # this is no longer equal to any single plant's marginal cost, because an
    # extra MWh here also changes what it costs to serve the neighbouring
    # hours. See "Prices" in the module docstring.
    price = []
    for t in HOURS:
        constraint = prob.constraints.get("balance_{}".format(t))
        pi = constraint.pi if constraint is not None else None
        price.append(float(pi) if pi is not None else np.nan)
    price = np.array(price, dtype=float)

    # Diagnostic, not a price: the marginal cost of the most expensive plant
    # actually generating. This is the old merit-order clearing price under
    # the name of what it really measures. Non-running plants are masked to
    # -inf rather than 0 so that a negative marginal cost could still be the
    # highest; hours with nothing running fall back to 0.0.
    running = output > TOL
    masked_mc = np.where(running, mc_vec[:, None], -np.inf)
    highest_running = np.where(running.any(axis=0), masked_mc.max(axis=0), 0.0)

    # Curtailment: profiled renewable energy that was available but not taken,
    # because demand was already met by cheaper or equal output. Distinct from
    # spill, which is energy that was generated and then thrown away.
    curtailed = np.maximum(0.0, avail - output)[par["profiled_mask"]].sum(axis=0)

    # Column order here is the column order of the CSV, so keep the generation
    # block ahead of the availability block. Availability is written out as
    # well as generation, because a profiled plant sitting at its resource
    # limit is at capacity even though it is far below nameplate. Anything
    # reading these results needs the hourly limit to tell "maxed out" from
    # "part loaded".
    columns = {"Hour": HOURS, "Demand (MWh)": demand_vec}
    for i, p in enumerate(PLANTS):
        columns["{} (MWh)".format(p)] = output[i]
    for i, p in enumerate(PLANTS):
        columns["{} Available (MWh)".format(p)] = avail[i]
    columns["Clearing Price ($/MWh)"] = price
    columns["Highest Running Cost ($/MWh)"] = highest_running
    columns["Production Cost ($)"] = mc_vec @ output
    columns["Ramp Up (MWh)"] = ramp_up_arr.sum(axis=0)
    columns["Ramp Down (MWh)"] = ramp_down_arr.sum(axis=0)
    columns["Ramp Cost ($)"] = ramp_cost_hourly
    columns["Market Cost ($)"] = price * demand_vec
    columns["Unserved Energy (MWh)"] = unserved_vec
    columns["Unserved Cost ($)"] = VOLL * unserved_vec
    columns["Spill (MWh)"] = spill_vec
    columns["Spill Cost ($)"] = SPILL_COST * spill_vec
    columns["Curtailment (MWh)"] = curtailed

    if np.isnan(price).any():
        print("  WARNING: the solver returned no dual for {} of {} hours, so "
              "the clearing price is missing there.\n"
              .format(int(np.isnan(price).sum()), len(HOURS)))

    return pd.DataFrame(columns)



def build_summary(par, results):
    """Per-plant totals: energy, capacity factor, hours running, cost."""

    n_hours = len(par["HOURS"])
    rows = []

    for p in par["PLANTS"]:
        series = results["{} (MWh)".format(p)]
        total = series.sum()
        max_possible = par["capacity"][p] * n_hours

        # Energy the plant could have produced given its resource. For a
        # thermal plant this is just nameplate around the clock; for wind and
        # solar it is limited by the hourly profile.
        is_profiled = p in par["profiled"]
        available = sum(par["availability"][p][t] for t in par["HOURS"])

        # Curtailment only means something for a profiled plant: energy the
        # resource offered but the dispatch did not take. Idle thermal
        # capacity is not curtailment, it is simply not being called on.
        curtailed = max(0.0, available - total) if is_profiled else 0.0

        # Movement, from the generation profile. Hour 1 has no predecessor so
        # the first difference is dropped rather than counted as a ramp.
        delta = series.to_numpy(dtype=float)[1:] - series.to_numpy(dtype=float)[:-1]
        ramp_up = float(np.maximum(0.0, delta).sum())
        ramp_down = float(np.maximum(0.0, -delta).sum())

        # A plant is last in the stack in an hour when it is running and its
        # marginal cost is the highest of anything running. Under ramping the
        # clearing price is the dual and no longer equals any plant's marginal
        # cost, so this is matched against the Highest Running Cost diagnostic
        # instead. It counts who was last in the merit order, which is not the
        # same as who set the price.
        is_running = series > TOL
        is_last = (results["Highest Running Cost ($/MWh)"]
                   - par["marginal_cost"][p]).abs() < 1e-6
        hours_last_in_stack = int((is_running & is_last).sum())

        rows.append({
            "Plant": p,
            "Technology": par["technology"][p],
            "Fuel": par["plant_fuel"][p],
            "Capacity (MW)": par["capacity"][p],
            "Profiled": is_profiled,
            "Marginal Cost ($/MWh)": par["marginal_cost"][p],
            "Ramp Rate (MW/hr)": par["ramp_rate"][p],
            "Ramping Efficiency (MWh/MWhTh)": par["ramp_efficiency"][p],
            "Ramp Premium ($/MWh)": par["ramp_cost"][p],
            "Total Generation (MWh)": total,
            "Available Energy (MWh)": available,
            "Curtailed (MWh)": curtailed,
            "Curtailment (%)": (100.0 * curtailed / available
                                if is_profiled and available > 0 else 0.0),
            "Share of Demand (%)": 100.0 * total / results["Demand (MWh)"].sum(),
            "Capacity Factor (%)": 100.0 * total / max_possible if max_possible else 0.0,
            "Availability Factor (%)": (100.0 * available / max_possible
                                        if max_possible else 0.0),
            "Hours Running": int(is_running.sum()),
            "Hours Last in Stack": hours_last_in_stack,
            "Total Ramp Up (MWh)": ramp_up,
            "Total Ramp Down (MWh)": ramp_down,
            # The premium only, matching the results file, so that summing
            # this column reproduces the objective's ramp term exactly.
            "Ramp Cost ($)": par["ramp_cost"][p] * (ramp_up + ramp_down),
            # Fuel and VOM only, deliberately excluding ramp cost, so that the
            # four components of the objective stay separable.
            "Production Cost ($)": total * par["marginal_cost"][p],
        })

    return pd.DataFrame(rows).sort_values("Marginal Cost ($/MWh)").reset_index(drop=True)


# --------------------------------------------------------------------------
# Step 8b - the merit order check
# --------------------------------------------------------------------------

def dispatch_ceiling(par, output):
    """The most each plant could have generated in each hour.

    Returns a (n_plants, n_hours) array laid out like `avail`.

    Two things cap a plant: its hourly availability, and how far it could
    climb from wherever it was in the previous hour. Hour 1 has no
    predecessor, so there only availability applies.
    """
    ceiling = np.array(par["avail"], dtype=float, copy=True)
    reachable = output[:, :-1] + par["ramp_rate_vec"][:, None]
    ceiling[:, 1:] = np.minimum(ceiling[:, 1:], reachable)
    return ceiling


def dispatch_floor(par, output):
    """The least each plant could have generated in each hour.

    The mirror of `dispatch_ceiling`. A ramp-down limit puts a floor under a
    plant: having been at some output last hour, it cannot drop further than
    its ramp rate this hour, plus whatever its own availability took away from
    underneath it.

    The floor is what makes a genuinely optimal dispatch capable of looking
    like a merit order violation, which is why `check_merit_order` needs it.
    """
    floor = np.zeros_like(par["avail"])
    floor[:, 1:] = (output[:, :-1]
                    - par["ramp_rate_vec"][:, None]
                    - par["forced_down"][:, 1:])
    return np.maximum(0.0, floor)


def check_merit_order(par, results):
    """Report where the dispatch appears to depart from merit order.

    The old invariant: in any hour, no plant may generate strictly below its
    dispatch ceiling while something strictly more expensive is generating.
    Cheap headroom must never be left unused above a running expensive plant.

    **This is a warning, not an error, and it no longer proves a bug.** That is
    a real loss of a correctness gate, so it is worth recording why it was
    given up.

    Ramping breaks the invariant in two separate ways, and both are optimal
    behaviour rather than mistakes:

    - A ramp *cost* means a cheap plant may deliberately hold back beneath a
      dearer one, because moving up this hour and back down next hour costs
      more in premium than the fuel it would save. The worked example in
      docs/ramping_semantics.md shows exactly this.
    - A ramp *down* limit puts a floor under a plant, so a cheap plant may run
      *low* now in order to be able to reach a low demand later without being
      stranded above it, spilling energy it cannot shed.

    No cheap check can tell either of those apart from a genuine modelling
    bug, because distinguishing them requires re-solving the LP. So the check
    keeps its arithmetic, drops its authority, and becomes a prompt to go and
    look rather than a proof that something is wrong.

    The floor is included so that a plant pinned above demand by its own
    ramp-down limit is not reported as "underused", which would be both wrong
    and extremely noisy.

    Equal-cost plants are not compared. Two plants on the same marginal cost
    may split output however the solver likes, and the strict comparison below
    never fires between them.
    """
    PLANTS, HOURS = par["PLANTS"], par["HOURS"]
    mc_vec = par["mc_vec"]

    # Rebuild the (n_plants, n_hours) arrays from the results table, so the
    # check is run against the numbers that were actually written out.
    output = np.array(
        [results["{} (MWh)".format(p)].to_numpy(dtype=float) for p in PLANTS])
    unserved_vec = results["Unserved Energy (MWh)"].to_numpy(dtype=float)

    ceiling = dispatch_ceiling(par, output)
    floor = dispatch_floor(par, output)

    # The comparator: the marginal cost of the most expensive thing generating
    # in each hour. Recomputed here rather than read from the Clearing Price
    # column, which is now the dual and is not any plant's marginal cost at
    # all. Using -inf when nothing is running makes the comparison vacuously
    # true, which is what it should be.
    running = output > TOL
    masked_mc = np.where(running, mc_vec[:, None], -np.inf)
    most_expensive = np.where(running.any(axis=0), masked_mc.max(axis=0), -np.inf)
    comparator = np.where(unserved_vec > TOL, VOLL, most_expensive)

    undercut = mc_vec[:, None] < comparator - TOL     # something dearer is on
    underused = output < ceiling - TOL                # and this plant has room
    pinned = output <= floor + TOL                    # but cannot go lower
    flagged = undercut & underused & ~pinned

    if not flagged.any():
        return

    headroom = ceiling - output
    # What the unused headroom would have been worth if it were free to use.
    # Under ramping this is an upper bound on any waste, not a bill: some of
    # it is legitimately forgone to avoid a ramp premium.
    value = float((headroom * (comparator - mc_vec[:, None]))[flagged].sum())

    rows = []
    for i, t_index in zip(*np.nonzero(flagged)):
        rows.append({
            "hour": HOURS[t_index],
            "plant": PLANTS[i],
            "mc": mc_vec[i],
            "gen": output[i, t_index],
            "ceiling": ceiling[i, t_index],
            "headroom": headroom[i, t_index],
            "above": describe_price_setter(par, comparator[t_index]),
        })
    rows.sort(key=lambda r: (r["hour"], r["plant"]))
    worst = max(rows, key=lambda r: r["headroom"])
    n_hours_affected = len(set(r["hour"] for r in rows))

    print("-" * 68)
    print("MERIT ORDER NOTE  ({} plant-hour(s) across {} hour(s))"
          .format(len(rows), n_hours_affected))
    print("-" * 68)
    print("  A plant generated below its ramp-adjusted ceiling while something")
    print("  more expensive was running. Under ramping this is often correct:")
    print("  holding back can be cheaper than paying to move, and a plant may")
    print("  stay low so that it can reach a low demand later. Worth a look,")
    print("  not proof of a bug.")
    print("  Cheap headroom left unused is worth at most ${:,.2f}.".format(value))
    print("")
    for r in rows[:10]:
        print("  hour {:>5}   {:<10} ${:>8.2f}/MWh   generated {:>9,.2f} of "
              "{:>9,.2f} MWh   ({:,.2f} MWh spare)   while {} was running"
              .format(r["hour"], r["plant"], r["mc"], r["gen"], r["ceiling"],
                      r["headroom"], r["above"]))
    if len(rows) > 10:
        print("  ... and {} more.".format(len(rows) - 10))
    print("")
    print("  Largest is hour {}: {} left {:,.2f} MWh unused.\n"
          .format(worst["hour"], worst["plant"], worst["headroom"]))


def describe_price_setter(par, price):
    """Name whatever is generating at `price`, for a diagnostic message."""
    if abs(price - VOLL) < TOL:
        return "unserved energy (VoLL)"
    if abs(price + SPILL_COST) < TOL:
        return "spilled energy"
    for p in par["PLANTS"]:
        if abs(par["marginal_cost"][p] - price) < TOL:
            return p
    return "something at ${:,.2f}/MWh".format(price)


# --------------------------------------------------------------------------
# Step 9 - reporting
# --------------------------------------------------------------------------

def report(par, results, summary, objective_value=None):
    print("-" * 68)
    print("MARGINAL COSTS  (fuel price / efficiency + VOM)")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:<10} {:>7.1f} MW   ${:>7.2f}/MWh{}"
              .format(r["Plant"], str(r["Technology"]), r["Capacity (MW)"],
                      r["Marginal Cost ($/MWh)"],
                      "   (profiled)" if r["Profiled"] else ""))

    print("\n" + "-" * 68)
    print("RAMPING  (premium is the extra cost of a moved MWh over a steady one)")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} rate {:>7.1f} MW/hr   ramp eff {:>5.3f}   "
              "premium ${:>7.2f}/MWh   moved {:>12,.1f} MWh   cost {:>14,.2f} $"
              .format(r["Plant"], r["Ramp Rate (MW/hr)"],
                      r["Ramping Efficiency (MWh/MWhTh)"], r["Ramp Premium ($/MWh)"],
                      r["Total Ramp Up (MWh)"] + r["Total Ramp Down (MWh)"],
                      r["Ramp Cost ($)"]))

    print("\n" + "-" * 68)
    print("DISPATCH SUMMARY")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:>12,.1f} MWh   CF {:>5.1f}%   running {:>4} h   last in stack {:>4} h"
              .format(r["Plant"], r["Total Generation (MWh)"], r["Capacity Factor (%)"],
                      r["Hours Running"], r["Hours Last in Stack"]))

    profiled = summary[summary["Profiled"]]
    if not profiled.empty:
        print("\n" + "-" * 68)
        print("RENEWABLE RESOURCE  (capacity factor is after curtailment)")
        print("-" * 68)
        for _, r in profiled.iterrows():
            print("  {:<10} resource {:>5.1f}%   used {:>5.1f}%   "
                  "available {:>10,.1f} MWh   curtailed {:>8,.1f} MWh ({:.1f}%)"
                  .format(r["Plant"], r["Availability Factor (%)"],
                          r["Capacity Factor (%)"], r["Available Energy (MWh)"],
                          r["Curtailed (MWh)"], r["Curtailment (%)"]))

    total_demand = results["Demand (MWh)"].sum()
    total_gen = summary["Total Generation (MWh)"].sum()
    prod_cost = results["Production Cost ($)"].sum()
    ramp_cost = results["Ramp Cost ($)"].sum()
    market_cost = results["Market Cost ($)"].sum()
    total_unserved = results["Unserved Energy (MWh)"].sum()
    unserved_cost = results["Unserved Cost ($)"].sum()
    total_spill = results["Spill (MWh)"].sum()
    spill_cost = results["Spill Cost ($)"].sum()
    objective = prod_cost + unserved_cost + ramp_cost + spill_cost

    print("\n" + "-" * 68)
    print("TOTALS OVER {} HOURS".format(len(results)))
    print("-" * 68)
    print("  Energy served              {:>16,.1f} MWh".format(total_demand - total_unserved))
    print("  Energy generated           {:>16,.1f} MWh".format(total_gen))
    if total_unserved > TOL:
        print("  Energy unserved            {:>16,.1f} MWh   ({:.2f}% of demand)"
              .format(total_unserved,
                      100.0 * total_unserved / total_demand if total_demand else 0.0))
    if total_spill > TOL:
        print("  Energy spilled             {:>16,.1f} MWh   ({:.2f}% of generation)"
              .format(total_spill,
                      100.0 * total_spill / total_gen if total_gen else 0.0))
    print("  Energy moved (ramping)     {:>16,.1f} MWh"
          .format(results["Ramp Up (MWh)"].sum() + results["Ramp Down (MWh)"].sum()))

    # The objective has four components. Print all four and then the sum, so
    # the reconciliation is a shown calculation rather than a claim.
    print("")
    print("  Production cost            {:>16,.2f} $      (fuel and VOM)".format(prod_cost))
    print("  Ramp cost                  {:>16,.2f} $      (premium on energy moved)"
          .format(ramp_cost))
    print("  Cost of unserved energy    {:>16,.2f} $      (VoLL x unserved)"
          .format(unserved_cost))
    print("  Cost of spilled energy     {:>16,.2f} $      (spill price x spilled)"
          .format(spill_cost))
    print("  LP objective               {:>16,.2f} $      (the four above)"
          .format(objective))

    # The line above is a claim that the four reported components add up to
    # what the solver actually minimised. Check it rather than assert it: if
    # a cost is ever double counted or dropped from a column, this is where it
    # shows up.
    if objective_value is not None:
        drift = abs(objective - objective_value)
        if drift > max(1e-3, 1e-9 * abs(objective_value)):
            print("  WARNING: those four components sum to ${:,.2f} but the solver "
                  "minimised\n           ${:,.2f}, a difference of ${:,.2f}. One of "
                  "the cost columns is\n           wrong."
                  .format(objective, objective_value, drift))
        else:
            print("  {:<26} {:>16} {:<6} (reconciles with the solver)"
                  .format("", "", ""))
    print("")
    print("  Average production cost    {:>16,.2f} $/MWh".format(prod_cost / total_demand))
    print("  Total market cost          {:>16,.2f} $      (clearing price x demand)"
          .format(market_cost))
    print("  Time-weighted avg price    {:>16,.2f} $/MWh"
          .format(results["Clearing Price ($/MWh)"].mean()))
    print("  Load-weighted avg price    {:>16,.2f} $/MWh".format(market_cost / total_demand))
    print("  Producer surplus           {:>16,.2f} $      (market - production)"
          .format(market_cost - prod_cost))
    if (results["Clearing Price ($/MWh)"] < -TOL).any():
        print("  note: the clearing price is negative in {} hour(s), so market cost "
              "there is\n        money paid to consumers to take power. See SPILL below."
              .format(int((results["Clearing Price ($/MWh)"] < -TOL).sum())))

    total_curtailed = results["Curtailment (MWh)"].sum()
    if par["profiled"]:
        avail = summary.loc[summary["Profiled"], "Available Energy (MWh)"].sum()
        used = summary.loc[summary["Profiled"], "Total Generation (MWh)"].sum()
        print("  Renewable energy used      {:>16,.1f} MWh   ({:.1f}% of demand)"
              .format(used, 100.0 * used / total_demand if total_demand else 0.0))
        print("  Renewable curtailed        {:>16,.1f} MWh   ({:.1f}% of available)"
              .format(total_curtailed,
                      100.0 * total_curtailed / avail if avail else 0.0))

    # Energy balance check. Unserved energy and spill are both part of the
    # balance, so they have to be counted here too.
    gap = abs(total_gen + total_unserved - total_spill - total_demand)
    print("\n  Energy balance check: |generation + unserved - spill - demand| = "
          "{:.6f} MWh {}".format(gap, "OK" if gap < 1e-3 else "<-- PROBLEM"))

    if total_unserved > TOL:
        short = results[results["Unserved Energy (MWh)"] > TOL]
        print("\n" + "-" * 68)
        print("SCARCITY  ({} hour(s) with unserved energy, priced at ${:,.2f}/MWh)"
              .format(len(short), VOLL))
        print("-" * 68)
        for _, r in short.head(10).iterrows():
            unmet = r["Unserved Energy (MWh)"]
            print("  hour {:>5}   demand {:>10,.1f} MWh   served {:>10,.1f} MWh   "
                  "short {:>9,.1f} MWh".format(
                      int(r["Hour"]), r["Demand (MWh)"], r["Demand (MWh)"] - unmet, unmet))
        if len(short) > 10:
            print("  ... and {} more hour(s). See the Unserved Energy column in "
                  "dispatch_results.csv.".format(len(short) - 10))

    if total_spill > TOL:
        dumped = results[results["Spill (MWh)"] > TOL]
        print("\n" + "-" * 68)
        print("SPILL  ({} hour(s) with energy thrown away, priced at ${:,.2f}/MWh)"
              .format(len(dumped), SPILL_COST))
        print("-" * 68)
        print("  Generation that could not be shed fast enough to follow demand down.")
        for _, r in dumped.head(10).iterrows():
            over = r["Spill (MWh)"]
            print("  hour {:>5}   demand {:>10,.1f} MWh   generated {:>10,.1f} MWh   "
                  "spilled {:>9,.1f} MWh   price ${:>10,.2f}/MWh".format(
                      int(r["Hour"]), r["Demand (MWh)"], r["Demand (MWh)"] + over,
                      over, r["Clearing Price ($/MWh)"]))
        if len(dumped) > 10:
            print("  ... and {} more hour(s). See the Spill column in "
                  "dispatch_results.csv.".format(len(dumped) - 10))

    # The clearing price is the dual, so under ramping it takes many distinct
    # values rather than a handful of plant marginal costs. Summarise its
    # distribution rather than enumerating it, and use the diagnostic column
    # to say who was last in the stack.
    price = results["Clearing Price ($/MWh)"]
    print("\n  Clearing price (the dual of the energy balance):")
    print("    min {:>10,.2f}   median {:>10,.2f}   max {:>10,.2f}   "
          "{} distinct value(s)"
          .format(price.min(), price.median(), price.max(),
                  price.round(6).nunique()))

    print("\n  Hours each plant was last in the stack:")
    for _, r in summary.iterrows():
        if r["Hours Last in Stack"]:
            print("    {:<10} {:>5} h  ({:>5.1f}%)   at ${:>7.2f}/MWh"
                  .format(r["Plant"], r["Hours Last in Stack"],
                          100.0 * r["Hours Last in Stack"] / len(results),
                          r["Marginal Cost ($/MWh)"]))
    print("")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Least-cost economic dispatch model.")
    parser.add_argument("--label", default=None,
                        help="short name for this run, used in the archive id")
    parser.add_argument("--notes", default=None,
                        help="longer description stored with the run")
    parser.add_argument("--no-archive", action="store_true",
                        help="solve and write results without archiving the run")
    parser.add_argument("--inputs", default=None,
                        help="read the four input CSVs from here instead of inputs/. "
                             "Useful for running the small worked example in "
                             "docs/ramping_semantics.md.")
    parser.add_argument("--results", default=None,
                        help="write the result CSVs here instead of results/")
    return parser.parse_args(argv)


def use_directories(inputs=None, results=None):
    """Point the model at a different pair of input and output folders.

    The paths are module-level constants because that keeps the common case,
    running the model over inputs/, entirely free of plumbing. Overriding them
    exists so that a small fixture can be solved without disturbing the real
    results, which is what the worked example in docs/ramping_semantics.md
    relies on.
    """
    global INPUTS_DIR, RESULTS_DIR, PLANTS_FILE, FUEL_FILE, DEMAND_FILE, PROFILE_FILE
    if inputs is not None:
        INPUTS_DIR = Path(inputs).resolve()
        PLANTS_FILE = INPUTS_DIR / "plants.csv"
        FUEL_FILE = INPUTS_DIR / "fuel.csv"
        DEMAND_FILE = INPUTS_DIR / "demand.csv"
        PROFILE_FILE = INPUTS_DIR / "profiles.csv"
    if results is not None:
        RESULTS_DIR = Path(results).resolve()


def main(argv=None):
    args = parse_args(argv)
    use_directories(args.inputs, args.results)

    print("\n" + "=" * 68)
    print("MY FIRST DISPATCH MODEL")
    print("=" * 68 + "\n")

    plants, fuel, demand, profile = load_data()
    print("Loaded {} plants, {} fuels, {} hours, {} profile rows.\n"
          .format(len(plants), len(fuel), len(demand), len(profile)))

    par = build_parameters(plants, fuel, demand, profile)
    if par["profiled"]:
        print("  profiled technologies: {}\n".format(
            ", ".join("{} ({})".format(p, par["technology"][p])
                      for p in sorted(par["profiled"]))))
    check_demand(par)
    check_capacity_adequacy(par)

    started = time.time()
    prob, gen, unserved, spill = build_and_solve(par)
    solve_seconds = round(time.time() - started, 3)

    results = build_results(par, prob, gen, unserved, spill)
    summary = build_summary(par, results)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    results_path = RESULTS_DIR / "dispatch_results.csv"
    summary_path = RESULTS_DIR / "plant_summary.csv"
    results.round(6).to_csv(results_path, index=False)
    summary.round(6).to_csv(summary_path, index=False)
    print("Results written:\n  {}\n  {}\n".format(results_path, summary_path))

    # Look over the dispatch before reporting on it. Under ramping this is a
    # note rather than a gate, so it neither stops the run nor blocks
    # archiving; see check_merit_order for why that authority was given up.
    check_merit_order(par, results)

    # Archive the run so it can be compared or restored later. A failure here
    # must not lose the results, which are already safely on disk. Runs over a
    # different pair of directories are not archived: the archive records the
    # state of inputs/ and results/, and a fixture run would misrepresent it.
    if args.no_archive or args.inputs or args.results:
        if args.inputs or args.results:
            print("Not archived: this run used custom input or output folders.\n")
    else:
        try:
            manifest = runstore.archive_run(
                label=args.label, notes=args.notes,
                solver_status=pulp.LpStatus[prob.status], seconds=solve_seconds)
            git = manifest["git"]
            print("Archived as run: {}".format(manifest["id"]))
            if git.get("short"):
                print("  git {}{}   compare with:  python run_archive/runs.py diff {} latest\n"
                      .format(git["short"],
                              " (dirty)" if git.get("dirty") else "",
                              manifest["id"]))
            else:
                print("")
        except Exception as exc:                             # noqa: BLE001
            print("WARNING: could not archive this run ({}: {}). "
                  "Results were still written.\n"
                  .format(type(exc).__name__, exc))

    report(par, results, summary, objective_value=pulp.value(prob.objective))


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:                              # noqa: BLE001
        print("\nERROR: {}: {}".format(type(exc).__name__, exc))
        sys.exit(1)
