"""
My First Dispatch Model (MFDM)
==============================

A least-cost economic dispatch model built with PuLP.

Sets
    PLANTS  power plants
    HOURS   hour-by-hour time steps
    FUELS   fuels

Parameters
    availability[p][t]  MW that plant p can supply in hour t. Thermal plants
                        are available at nameplate around the clock; wind and
                        solar are nameplate scaled by an hourly capacity
                        factor read from profiles.csv.
    marginal_cost[p]    fuel_price / efficiency + VOM   ($/MWh)
    demand[t]           MWh required in hour t

Decision variables
    gen[p][t]           MWh generated by plant p in hour t
    unserved[t]         MWh of demand left unmet in hour t

Objective
    minimise sum over p, t of marginal_cost[p] * gen[p][t]
           + sum over t of VOLL * unserved[t]

Constraints
    energy balance  sum over p of gen[p][t] + unserved[t] == demand[t]
    capacity        gen[p][t] <= availability[p][t]

Scarcity
    Demand that no plant can cover is not an error, it is expensive. The
    `unserved` variable lets the balance always be met, priced at VOLL (the
    value of lost load), which sits far above every plant's marginal cost so
    the solver only reaches for it once all real capacity is exhausted. The
    consequence is that the energy balance can no longer be infeasible, so a
    non-optimal solver status now means a bug in the model rather than a
    problem with the data.

After solving, the hourly market clearing price is taken as the marginal cost
of the most expensive plant running in that hour, or VOLL in an hour with
unserved energy, and is cross-checked against the dual (shadow price) of the
energy balance constraint.

Reads the four CSVs in inputs/ and writes dispatch_results.csv and
plant_summary.csv into results/. Run dashboard/dashboard.py afterwards to
explore the results interactively.

Array layout
    Hourly quantities are held as numpy arrays of shape (n_plants, n_hours),
    with rows ordered by PLANTS and columns ordered by HOURS. The parameter
    dictionary carries `avail` (availability), `mc_vec` (marginal cost, one
    per plant), `demand_vec` and `profiled_mask` in this form. The older
    dict-of-dicts views (`availability`, `marginal_cost`, `demand`) are kept
    alongside them because the reporting code reads more clearly with named
    lookups; they are derived from the arrays so the two cannot drift apart.
"""

from pathlib import Path
import argparse
import sys
import time

import numpy as np
import pandas as pd
import pulp

# runstore lives in run_archive/, which is a sibling folder rather than a
# package, so it has to be put on the import path before importing it.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "run_archive"))
import runstore


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent          # model/
REPO_ROOT = BASE_DIR.parent

# Inputs are read from inputs/ and results are written to results/, both at
# the repo root, so the model folder holds only code.
INPUTS_DIR = REPO_ROOT / "inputs"
RESULTS_DIR = REPO_ROOT / "results"

PLANTS_FILE = INPUTS_DIR / "plants.csv"
FUEL_FILE = INPUTS_DIR / "fuel.csv"
DEMAND_FILE = INPUTS_DIR / "demand.csv"
PROFILE_FILE = INPUTS_DIR / "profiles.csv"


# Generation below this is treated as "not running" when finding the marginal
# plant, so that solver round-off does not set the price.
TOL = 1e-6

# Value of Lost Load: what an hour of unmet demand is worth to the people who
# go without. Demand the fleet cannot cover is priced at this rather than
# making the model infeasible. 8300 $/MWh is the low end of the European
# Commission JRC estimate for Greece; see docs/research/scarcity_pricing.md.
# It must stay well above the most expensive plant's marginal cost, otherwise
# the solver would rather shed load than run that plant.
VOLL = 8300.0

# Technologies whose output is limited by an hourly resource profile rather
# than being available at nameplate around the clock. The value is the token
# looked for in the profiles.csv column headers.
PROFILE_TECHNOLOGIES = {
    "Wind": "wind",
    "Solar": "solar",
}


# --------------------------------------------------------------------------
# Step 1 - load data
# --------------------------------------------------------------------------

def load_data():
    """Read the four input CSVs and return them as DataFrames."""
    for path in (PLANTS_FILE, FUEL_FILE, DEMAND_FILE, PROFILE_FILE):
        if not path.exists():
            raise FileNotFoundError("Could not find input file: {}".format(path))

    # keep_default_na=False so that Solar's fuel of "None" stays the literal
    # string "None" rather than becoming NaN.
    plants = pd.read_csv(PLANTS_FILE, keep_default_na=False)
    fuel = pd.read_csv(FUEL_FILE)
    demand = pd.read_csv(DEMAND_FILE)

    # profiles.csv has two header rows: a region row (",FRA,FRA") and a
    # series row ("hours,wind (won),solar (solEB)"). Read both, then flatten
    # to single names of the form "FRA wind (won)", keeping the region so
    # multi-region files stay unambiguous.
    profile = pd.read_csv(PROFILE_FILE, header=[0, 1])
    flat = []
    for region, series in profile.columns:
        region = "" if str(region).startswith("Unnamed") else str(region).strip()
        series = str(series).strip()
        flat.append("{} {}".format(region, series).strip())
    profile.columns = flat

    # Tidy up stray whitespace in the text columns.
    for df in (plants, fuel, demand):
        df.columns = [c.strip() for c in df.columns]
    for col in ("Plant", "Technology", "Fuel"):
        plants[col] = plants[col].astype(str).str.strip()
    fuel["Technology"] = fuel["Technology"].astype(str).str.strip()

    return plants, fuel, demand, profile


# --------------------------------------------------------------------------
# Steps 2 and 3 - sets and parameters
# --------------------------------------------------------------------------

def build_parameters(plants, fuel, demand, profile):
    """Turn the raw DataFrames into the sets and parameter dictionaries."""

    # --- sets ---
    PLANTS = list(plants["Plant"])
    HOURS = [int(h) for h in demand["Hour"]]

    # --- fuel prices ---
    #Anything not listed is free.
    fuel_price = dict(zip(fuel["Technology"], fuel["Fuel Price ($/MWhTh)"].astype(float)))

    def price_of(fuel_name):
        if fuel_name is None:
            return 0.0
        if str(fuel_name).strip().lower() in ("none", "nan", ""):
            return 0.0
        if fuel_name not in fuel_price:
            print("  note: no fuel price listed for '{}', treating as $0/MWhTh".format(fuel_name))
            return 0.0
        return fuel_price[fuel_name]

    # --- per plant parameters ---
    capacity = {}
    efficiency = {}
    vom = {}
    technology = {}
    plant_fuel = {}
    marginal_cost = {}

    for _, row in plants.iterrows():
        p = row["Plant"]
        capacity[p] = float(row["Capacity (MW)"])
        efficiency[p] = float(row["Efficiency (MWh/MWhTh)"])
        vom[p] = float(row["VOM ($/MWh)"])
        technology[p] = row["Technology"]
        plant_fuel[p] = row["Fuel"]

        if efficiency[p] <= 0:
            raise ValueError("Plant {} has a non-positive efficiency".format(p))

        # marginal cost = fuel cost / efficiency + VOM
        marginal_cost[p] = price_of(row["Fuel"]) / efficiency[p] + vom[p]

    # --- availability: nameplate capacity, scaled by an hourly resource
    # profile for the technologies that have one ---
    #
    # Built as a single (n_plants, n_hours) array. Rows for plants without a
    # profile stay at a factor of 1.0, i.e. available at nameplate around the
    # clock. The dict-of-dicts view is derived from the array below.
    profile_factors = build_profile_factors(profile, technology, HOURS)

    cap_vec = np.array([capacity[p] for p in PLANTS], dtype=float)
    mc_vec = np.array([marginal_cost[p] for p in PLANTS], dtype=float)
    profiled_mask = np.array([p in profile_factors for p in PLANTS], dtype=bool)

    factors_matrix = np.ones((len(PLANTS), len(HOURS)), dtype=float)
    for i, p in enumerate(PLANTS):
        factors = profile_factors.get(p)
        if factors is not None:
            factors_matrix[i] = [factors[t] for t in HOURS]

    avail = cap_vec[:, None] * factors_matrix

    # Legacy dict-of-dicts view, derived from `avail` so the two agree by
    # construction.
    availability = {p: dict(zip(HOURS, avail[i]))
                    for i, p in enumerate(PLANTS)}

    # --- demand ---
    demand_col = [c for c in demand.columns if c.lower().startswith("demand")][0]
    demand_vec = demand[demand_col].astype(float).to_numpy()
    demand_by_hour = dict(zip(HOURS, demand_vec))

    return {
        "PLANTS": PLANTS,
        "HOURS": HOURS,
        "capacity": capacity,
        "efficiency": efficiency,
        "vom": vom,
        "technology": technology,
        "plant_fuel": plant_fuel,
        "marginal_cost": marginal_cost,
        "availability": availability,
        "profiled": set(profile_factors),
        "demand": demand_by_hour,
        # Array views, see "Array layout" in the module docstring.
        "avail": avail,
        "cap_vec": cap_vec,
        "mc_vec": mc_vec,
        "demand_vec": demand_vec,
        "profiled_mask": profiled_mask,
    }


def build_profile_factors(profile, technology, HOURS):
    """Map each profiled plant to its hourly capacity factor.

    Returns {plant: {hour: factor}} containing only the plants whose
    technology has a matching column in profiles.csv. Plants absent from the
    result are treated as available at nameplate in every hour.
    """
    hour_col = profile.columns[0]
    available_hours = set(int(h) for h in profile[hour_col])

    missing = [t for t in HOURS if t not in available_hours]
    if missing:
        raise ValueError(
            "profiles.csv is missing {} of the {} hours in demand.csv "
            "(first missing: hour {}).".format(len(missing), len(HOURS), missing[0]))

    # Restrict profileto the modelled hours
    idx = profile[hour_col].astype(int)
    sub = profile.set_index(idx).loc[HOURS]

    factors = {}
    for plant, tech in technology.items():
        token = PROFILE_TECHNOLOGIES.get(tech)
        if token is None:
            continue

        matches = [c for c in profile.columns
                   if c is not hour_col and token in c.lower()]
        if not matches:
            print("  note: technology '{}' has no profile column in profiles.csv, "
                  "treating {} as always available".format(tech, plant))
            continue
        if len(matches) > 1:
            raise ValueError(
                "Technology '{}' matches more than one profile column: {}. "
                "Column names must be unambiguous.".format(tech, matches))

        series = sub[matches[0]].astype(float)
        lo, hi = float(series.min()), float(series.max())
        if lo < -TOL or hi > 1.0 + TOL:
            raise ValueError(
                "Profile column '{}' has values outside 0 to 1 (min {:.4f}, "
                "max {:.4f}). Expected capacity factors.".format(matches[0], lo, hi))

        factors[plant] = {t: float(v) for t, v in zip(HOURS, series.values)}

    return factors


def check_demand(par):
    "Flag suspicious demand values"
    zeros = [t for t in par["HOURS"] if par["demand"][t] <= 0.0]
    if zeros:
        shown = ", ".join(str(t) for t in zeros[:10])
        more = " and {} more".format(len(zeros) - 10) if len(zeros) > 10 else ""
        print("  WARNING: demand is zero or negative in {} hour(s): {}{}."
              .format(len(zeros), shown, more))
        print("           Check demand.csv. The model will dispatch nothing "
              "in those hours.\n")


def check_capacity_adequacy(par):
    "Warn before solving if demand exceeds everything the fleet can offer"
    short = []
    for t in par["HOURS"]:
        total = sum(par["availability"][p][t] for p in par["PLANTS"])
        if total < par["demand"][t] - TOL:
            short.append((t, par["demand"][t], total))

    if short:
        t, d, a = short[0]
        worst = max(short, key=lambda r: r[1] - r[2])
        print("  WARNING: demand exceeds available capacity in {} of {} hour(s)."
              .format(len(short), len(par["HOURS"])))
        print("           First is hour {}: demand {:,.2f} MWh vs {:,.2f} MW available."
              .format(t, d, a))
        print("           Worst is hour {}, short by {:,.2f} MW."
              .format(worst[0], worst[1] - worst[2]))
        print("           The shortfall will be priced at ${:,.2f}/MWh (VoLL). "
              "Check plants.csv and demand.csv.\n".format(VOLL))

# --------------------------------------------------------------------------
# Steps 4 to 7 - build and solve the LP
# --------------------------------------------------------------------------

def build_and_solve(par):
    "Build the dispatch LP, solve it, and return the model and variables."

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]

    prob = pulp.LpProblem("Economic_Dispatch", pulp.LpMinimize)

    # --- Step 4: decision variables ---
    gen = pulp.LpVariable.dicts("gen", (PLANTS, HOURS), lowBound=0, cat="Continuous")

    # Unmet demand, one per hour. See "Scarcity" in the module docstring.
    unserved = pulp.LpVariable.dicts("unserved", HOURS, lowBound=0, cat="Continuous")

    # --- Step 5: objective, total production cost plus the cost of any
    # demand left unserved ---
    prob += (
        pulp.lpSum(par["marginal_cost"][p] * gen[p][t] for p in PLANTS for t in HOURS)
        + pulp.lpSum(VOLL * unserved[t] for t in HOURS),
        "Total_Production_Cost",
    )

    # --- Step 6a: energy balance, one per hour ---
    # Named so the dual (shadow price) can be pulled out after solving.
    for t in HOURS:
        prob += (
            pulp.lpSum(gen[p][t] for p in PLANTS) + unserved[t] == par["demand"][t],
            "balance_{}".format(t),
        )

    # --- Step 6b: capacity, one per plant per hour ---
    for p in PLANTS:
        for t in HOURS:
            prob += (
                gen[p][t] <= par["availability"][p][t],
                "cap_{}_{}".format(p.replace(" ", "_"), t),
            )

    # --- Step 7: solve ---
    print("Solving: {} variables, {} constraints ...".format(
        len(PLANTS) * len(HOURS) + len(HOURS), len(prob.constraints)))
    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    status = pulp.LpStatus[prob.status]
    if status != "Optimal":
        raise RuntimeError(
            "Solver did not reach an optimal solution (status: {}). "
            "Because unserved demand is priced at VoLL rather than forbidden, "
            "the energy balance can always be met, so this is a bug in how the "
            "LP is built rather than a problem with the input data.".format(status)
        )
    print("Solver status: {}\n".format(status))

    return prob, gen, unserved


# --------------------------------------------------------------------------
# Step 8 - results and clearing price
# --------------------------------------------------------------------------

def build_results(par, prob, gen, unserved):
    """Assemble the hourly results table, including the clearing price."""

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]
    avail, mc_vec, demand_vec = par["avail"], par["mc_vec"], par["demand_vec"]

    # Pull the solution out of the solver once, into a (n_plants, n_hours)
    # array laid out the same way as `avail`. Everything below is then plain
    # array arithmetic. `or 0.0` guards against a None from an unused
    # variable.
    output = np.array(
        [[gen[p][t].value() or 0.0 for t in HOURS] for p in PLANTS],
        dtype=float)

    unserved_vec = np.array([unserved[t].value() or 0.0 for t in HOURS], dtype=float)
    scarce = unserved_vec > TOL

    # Clearing price, method 1: merit order. The most expensive plant actually
    # generating sets the price. Non-running plants are masked to -inf rather
    # than 0 so that a negative marginal cost could still set the price; hours
    # with nothing running fall back to 0.0.
    running = output > TOL
    masked_mc = np.where(running, mc_vec[:, None], -np.inf)
    price_merit = np.where(running.any(axis=0), masked_mc.max(axis=0), 0.0)

    # In an hour with unserved energy the marginal MWh is not supplied by any
    # plant, it is shed. Lost load is the marginal "unit", so it sets the
    # price at VOLL. Without this the hour would price at the most expensive
    # running plant, understating the scarcity and disagreeing with the dual.
    price_merit = np.where(scarce, VOLL, price_merit)

    # Clearing price, method 2: the dual of the energy balance constraint.
    # Still a per-hour loop, because these are PuLP constraint objects.
    price_dual = []
    for t in HOURS:
        constraint = prob.constraints.get("balance_{}".format(t))
        price_dual.append(
            constraint.pi if constraint is not None and constraint.pi is not None else None)

    # These agree except in degenerate hours where a plant sits exactly on its
    # cap. Report the merit-order value as briefed, but flag any gap.
    mismatches = sum(
        1 for d, m in zip(price_dual, price_merit)
        if d is not None and abs(d - m) > 1e-4)

    # Curtailment: profiled renewable energy that was available but not taken,
    # because demand was already met by cheaper or equal output.
    curtailed = np.maximum(0.0, avail - output)[par["profiled_mask"]].sum(axis=0)

    # Column order here is the column order of the CSV, so keep the generation
    # block ahead of the availability block. Availability is written out as
    # well as generation, because a profiled plant sitting at its resource
    # limit is at capacity even though it is far below nameplate. Anything
    # reading these results needs the hourly limit to tell "maxed out" from
    # "part loaded".
    columns = {"Hour": HOURS, "Demand (MWh)": demand_vec}
    for i, p in enumerate(PLANTS):
        columns["{} (MWh)".format(p)] = output[i]
    for i, p in enumerate(PLANTS):
        columns["{} Available (MWh)".format(p)] = avail[i]
    columns["Clearing Price ($/MWh)"] = price_merit
    columns["Shadow Price ($/MWh)"] = price_dual
    columns["Production Cost ($)"] = mc_vec @ output
    columns["Market Cost ($)"] = price_merit * demand_vec
    columns["Unserved Energy (MWh)"] = unserved_vec
    columns["Unserved Cost ($)"] = VOLL * unserved_vec
    columns["Curtailment (MWh)"] = curtailed

    if mismatches:
        print("  note: merit-order and shadow prices differ in {} of {} hours "
              "(expected in degenerate hours where a plant sits exactly on its cap)\n"
              .format(mismatches, len(HOURS)))

    return pd.DataFrame(columns)



def build_summary(par, results):
    """Per-plant totals: energy, capacity factor, hours running, cost."""

    n_hours = len(par["HOURS"])
    rows = []

    for p in par["PLANTS"]:
        series = results["{} (MWh)".format(p)]
        total = series.sum()
        max_possible = par["capacity"][p] * n_hours

        # Energy the plant could have produced given its resource. For a
        # thermal plant this is just nameplate around the clock; for wind and
        # solar it is limited by the hourly profile.
        is_profiled = p in par["profiled"]
        available = sum(par["availability"][p][t] for t in par["HOURS"])

        # Curtailment only means something for a profiled plant: energy the
        # resource offered but the dispatch did not take. Idle thermal
        # capacity is not curtailment, it is simply not being called on.
        curtailed = max(0.0, available - total) if is_profiled else 0.0

        # A plant sets the price in an hour when it is running and its
        # marginal cost equals the clearing price.
        is_running = series > TOL
        is_marginal = (results["Clearing Price ($/MWh)"] - par["marginal_cost"][p]).abs() < 1e-6
        hours_setting_price = int((is_running & is_marginal).sum())

        rows.append({
            "Plant": p,
            "Technology": par["technology"][p],
            "Fuel": par["plant_fuel"][p],
            "Capacity (MW)": par["capacity"][p],
            "Profiled": is_profiled,
            "Marginal Cost ($/MWh)": par["marginal_cost"][p],
            "Total Generation (MWh)": total,
            "Available Energy (MWh)": available,
            "Curtailed (MWh)": curtailed,
            "Curtailment (%)": (100.0 * curtailed / available
                                if is_profiled and available > 0 else 0.0),
            "Share of Demand (%)": 100.0 * total / results["Demand (MWh)"].sum(),
            "Capacity Factor (%)": 100.0 * total / max_possible if max_possible else 0.0,
            "Availability Factor (%)": (100.0 * available / max_possible
                                        if max_possible else 0.0),
            "Hours Running": int(is_running.sum()),
            "Hours Setting Price": hours_setting_price,
            "Production Cost ($)": total * par["marginal_cost"][p],
        })

    return pd.DataFrame(rows).sort_values("Marginal Cost ($/MWh)").reset_index(drop=True)


# --------------------------------------------------------------------------
# Step 8b - the merit order check
# --------------------------------------------------------------------------

def dispatch_ceiling(par, output):
    """The most each plant could have generated in each hour.

    Returns a (n_plants, n_hours) array laid out like `avail`.

    Today a plant's ceiling is simply its hourly availability, so this returns
    `avail` untouched and ignores `output`. It exists as a function anyway
    because it is the one place that changes when ramp rates arrive: a plant's
    real ceiling then becomes the lower of its availability and the most it
    could reach from last hour's output,

        np.minimum(par["avail"], previous_output + ramp_up_rate)

    which is why `output` is already an argument. check_merit_order below is
    written against this ceiling and never mentions availability, so it needs
    no changes when that happens.

    A boundary worth knowing about in advance: this handles ramping *up*.
    A ramp-*down* limit is different in kind, because it puts a floor under a
    plant rather than a ceiling over it, and a floor can make a genuinely
    optimal dispatch look like a merit order violation. A cheap plant may hold
    back in one hour so that it can drop to a low demand in the next without
    being stranded above it. When ramp-down limits are added, the check below
    stops being a proof of a bug and becomes a prompt to go and look.
    """
    return par["avail"]


def check_merit_order(par, results):
    """Assert that the dispatch respects merit order, hour by hour.

    The invariant: in any hour, no plant may generate strictly below its
    dispatch ceiling while something strictly more expensive is generating.
    Put the other way round, cheap headroom must never be left unused above a
    running expensive plant.

    Stating it against the ceiling rather than against nameplate is what makes
    it checkable. A solar farm at its midday resource limit is not skipping
    its turn in the merit order, it is exhausted, and judging it against
    nameplate would report it as a violation in every sunny hour.

    "Something strictly more expensive" includes unserved energy, which at
    VOLL is the most expensive thing in the stack. So in an hour with a
    shortfall the invariant demands that every plant be at its ceiling, which
    is exactly right: load should never be shed while any headroom remains.
    Unserved energy only ever appears on the expensive side of the comparison,
    never as the underused cheap side, because nothing is priced above it.

    Equal-cost plants are not asserted about. Two plants on the same marginal
    cost may split output however the solver likes, and the strict comparison
    below simply never fires between them.
    """
    PLANTS, HOURS = par["PLANTS"], par["HOURS"]
    mc_vec = par["mc_vec"]

    # Rebuild the (n_plants, n_hours) arrays from the results table, so the
    # check is run against the numbers that were actually written out.
    output = np.array(
        [results["{} (MWh)".format(p)].to_numpy(dtype=float) for p in PLANTS])
    unserved_vec = results["Unserved Energy (MWh)"].to_numpy(dtype=float)

    ceiling = dispatch_ceiling(par, output)

    # The comparator: the marginal cost of the most expensive thing generating
    # in each hour. Deliberately recomputed here rather than read from the
    # Clearing Price column, for two reasons. That column falls back to 0.0 in
    # an hour with nothing running, which would make a plant with a negative
    # marginal cost look undercut by a price that no one is actually offering.
    # Using -inf instead makes the invariant vacuously true when nothing is
    # running, which is what it should be. It also keeps this check
    # independent of any later decision about what price to display.
    running = output > TOL
    masked_mc = np.where(running, mc_vec[:, None], -np.inf)
    most_expensive = np.where(running.any(axis=0), masked_mc.max(axis=0), -np.inf)
    comparator = np.where(unserved_vec > TOL, VOLL, most_expensive)

    undercut = mc_vec[:, None] < comparator - TOL     # something dearer is on
    underused = output < ceiling - TOL                # and this plant has room
    violations = undercut & underused

    if not violations.any():
        return

    headroom = ceiling - output
    # What the violation cost: every MWh of cheap headroom left unused had to
    # be covered by something dearer, at the difference in price.
    wasted = float((headroom * (comparator - mc_vec[:, None]))[violations].sum())

    rows = []
    for i, t_index in zip(*np.nonzero(violations)):
        rows.append({
            "hour": HOURS[t_index],
            "plant": PLANTS[i],
            "mc": mc_vec[i],
            "gen": output[i, t_index],
            "ceiling": ceiling[i, t_index],
            "headroom": headroom[i, t_index],
            "above": describe_price_setter(par, comparator[t_index]),
        })
    rows.sort(key=lambda r: (r["hour"], r["plant"]))
    worst = max(rows, key=lambda r: r["headroom"])
    n_hours_affected = len(set(r["hour"] for r in rows))

    lines = [
        "Merit order violated in {} plant-hour(s) across {} hour(s). A plant "
        "generated below its ceiling while something more expensive was "
        "running, so this dispatch is not least cost.".format(
            len(rows), n_hours_affected),
        "Cost of the violation: ${:,.2f}.".format(wasted),
        "",
    ]
    for r in rows[:10]:
        lines.append(
            "  hour {:>5}   {:<10} ${:>8.2f}/MWh   generated {:>9,.2f} of "
            "{:>9,.2f} MWh   ({:,.2f} MWh spare)   while {} was running"
            .format(r["hour"], r["plant"], r["mc"], r["gen"], r["ceiling"],
                    r["headroom"], r["above"]))
    if len(rows) > 10:
        lines.append("  ... and {} more.".format(len(rows) - 10))
    lines.append("")
    lines.append(
        "Worst is hour {}: {} left {:,.2f} MWh unused.".format(
            worst["hour"], worst["plant"], worst["headroom"]))

    raise ValueError("\n".join(lines))


def describe_price_setter(par, price):
    """Name whatever is generating at `price`, for a diagnostic message."""
    if abs(price - VOLL) < TOL:
        return "unserved energy (VoLL)"
    for p in par["PLANTS"]:
        if abs(par["marginal_cost"][p] - price) < TOL:
            return p
    return "something at ${:,.2f}/MWh".format(price)


# --------------------------------------------------------------------------
# Step 9 - reporting
# --------------------------------------------------------------------------

def report(par, results, summary):
    print("-" * 68)
    print("MARGINAL COSTS  (fuel price / efficiency + VOM)")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:<10} {:>7.1f} MW   ${:>7.2f}/MWh{}"
              .format(r["Plant"], str(r["Technology"]), r["Capacity (MW)"],
                      r["Marginal Cost ($/MWh)"],
                      "   (profiled)" if r["Profiled"] else ""))

    print("\n" + "-" * 68)
    print("DISPATCH SUMMARY")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:>12,.1f} MWh   CF {:>5.1f}%   running {:>4} h   sets price {:>4} h"
              .format(r["Plant"], r["Total Generation (MWh)"], r["Capacity Factor (%)"],
                      r["Hours Running"], r["Hours Setting Price"]))

    profiled = summary[summary["Profiled"]]
    if not profiled.empty:
        print("\n" + "-" * 68)
        print("RENEWABLE RESOURCE  (capacity factor is after curtailment)")
        print("-" * 68)
        for _, r in profiled.iterrows():
            print("  {:<10} resource {:>5.1f}%   used {:>5.1f}%   "
                  "available {:>10,.1f} MWh   curtailed {:>8,.1f} MWh ({:.1f}%)"
                  .format(r["Plant"], r["Availability Factor (%)"],
                          r["Capacity Factor (%)"], r["Available Energy (MWh)"],
                          r["Curtailed (MWh)"], r["Curtailment (%)"]))

    total_demand = results["Demand (MWh)"].sum()
    total_gen = summary["Total Generation (MWh)"].sum()
    prod_cost = results["Production Cost ($)"].sum()
    market_cost = results["Market Cost ($)"].sum()
    total_unserved = results["Unserved Energy (MWh)"].sum()

    print("\n" + "-" * 68)
    print("TOTALS OVER {} HOURS".format(len(results)))
    print("-" * 68)
    print("  Energy served              {:>16,.1f} MWh".format(total_demand - total_unserved))
    print("  Energy generated           {:>16,.1f} MWh".format(total_gen))
    if total_unserved > TOL:
        print("  Energy unserved            {:>16,.1f} MWh   ({:.2f}% of demand)"
              .format(total_unserved,
                      100.0 * total_unserved / total_demand if total_demand else 0.0))
    print("  Total production cost      {:>16,.2f} ${}"
          .format(prod_cost, "" if total_unserved > TOL else "      (the LP objective)"))
    print("  Average production cost    {:>16,.2f} $/MWh".format(prod_cost / total_demand))
    if total_unserved > TOL:
        unserved_cost = results["Unserved Cost ($)"].sum()
        print("  Cost of unserved energy    {:>16,.2f} $      (VoLL x unserved)"
              .format(unserved_cost))
        print("  LP objective               {:>16,.2f} $      (production + unserved)"
              .format(prod_cost + unserved_cost))
    print("  Total market cost          {:>16,.2f} $      (clearing price x demand)"
          .format(market_cost))
    print("  Time-weighted avg price    {:>16,.2f} $/MWh"
          .format(results["Clearing Price ($/MWh)"].mean()))
    print("  Load-weighted avg price    {:>16,.2f} $/MWh".format(market_cost / total_demand))
    print("  Producer surplus           {:>16,.2f} $      (market - production)"
          .format(market_cost - prod_cost))

    total_curtailed = results["Curtailment (MWh)"].sum()
    if par["profiled"]:
        avail = summary.loc[summary["Profiled"], "Available Energy (MWh)"].sum()
        used = summary.loc[summary["Profiled"], "Total Generation (MWh)"].sum()
        print("  Renewable energy used      {:>16,.1f} MWh   ({:.1f}% of demand)"
              .format(used, 100.0 * used / total_demand if total_demand else 0.0))
        print("  Renewable curtailed        {:>16,.1f} MWh   ({:.1f}% of available)"
              .format(total_curtailed,
                      100.0 * total_curtailed / avail if avail else 0.0))

    # Energy balance check. Unserved energy is part of the balance, so it has
    # to be counted here too, otherwise every scarce hour looks like a bug.
    gap = abs(total_gen + total_unserved - total_demand)
    print("\n  Energy balance check: |generation + unserved - demand| = {:.6f} MWh {}"
          .format(gap, "OK" if gap < 1e-3 else "<-- PROBLEM"))

    if total_unserved > TOL:
        short = results[results["Unserved Energy (MWh)"] > TOL]
        print("\n" + "-" * 68)
        print("SCARCITY  ({} hour(s) with unserved energy, priced at ${:,.2f}/MWh)"
              .format(len(short), VOLL))
        print("-" * 68)
        for _, r in short.head(10).iterrows():
            unmet = r["Unserved Energy (MWh)"]
            print("  hour {:>5}   demand {:>10,.1f} MWh   served {:>10,.1f} MWh   "
                  "short {:>9,.1f} MWh".format(
                      int(r["Hour"]), r["Demand (MWh)"], r["Demand (MWh)"] - unmet, unmet))
        if len(short) > 10:
            print("  ... and {} more hour(s). See the Unserved Energy column in "
                  "dispatch_results.csv.".format(len(short) - 10))

    print("\n  Hours at each clearing price:")
    for price, count in sorted(results["Clearing Price ($/MWh)"].value_counts().items()):
        setter = [p for p in par["PLANTS"] if abs(par["marginal_cost"][p] - price) < 1e-6]
        if abs(price - VOLL) < 1e-6:
            who = "unserved energy (VoLL)"
        else:
            who = setter[0] if setter else "n/a"
        print("    ${:>7.2f}/MWh   {:>4} h  ({:>5.1f}%)   set by {}"
              .format(price, count, 100.0 * count / len(results), who))
    print("")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Least-cost economic dispatch model.")
    parser.add_argument("--label", default=None,
                        help="short name for this run, used in the archive id")
    parser.add_argument("--notes", default=None,
                        help="longer description stored with the run")
    parser.add_argument("--no-archive", action="store_true",
                        help="solve and write results without archiving the run")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    print("\n" + "=" * 68)
    print("MY FIRST DISPATCH MODEL")
    print("=" * 68 + "\n")

    plants, fuel, demand, profile = load_data()
    print("Loaded {} plants, {} fuels, {} hours, {} profile rows.\n"
          .format(len(plants), len(fuel), len(demand), len(profile)))

    par = build_parameters(plants, fuel, demand, profile)
    if par["profiled"]:
        print("  profiled technologies: {}\n".format(
            ", ".join("{} ({})".format(p, par["technology"][p])
                      for p in sorted(par["profiled"]))))
    check_demand(par)
    check_capacity_adequacy(par)

    started = time.time()
    prob, gen, unserved = build_and_solve(par)
    solve_seconds = round(time.time() - started, 3)

    results = build_results(par, prob, gen, unserved)
    summary = build_summary(par, results)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    results_path = RESULTS_DIR / "dispatch_results.csv"
    summary_path = RESULTS_DIR / "plant_summary.csv"
    results.round(6).to_csv(results_path, index=False)
    summary.round(6).to_csv(summary_path, index=False)
    print("Results written:\n  {}\n  {}\n".format(results_path, summary_path))

    # Check the dispatch before standing behind it. This runs after the CSVs
    # are written so that a failed run still leaves the numbers on disk to
    # look at, but before archiving, so a run known to be wrong never enters
    # the archive and never gets a summary printed that implies it is fine.
    try:
        check_merit_order(par, results)
    except ValueError as exc:
        raise ValueError("{}\n\nResults were still written to {} so the "
                         "dispatch can be inspected.".format(exc, results_path))

    # Archive the run so it can be compared or restored later. A failure here
    # must not lose the results, which are already safely on disk.
    if not args.no_archive:
        try:
            manifest = runstore.archive_run(
                label=args.label, notes=args.notes,
                solver_status=pulp.LpStatus[prob.status], seconds=solve_seconds)
            git = manifest["git"]
            print("Archived as run: {}".format(manifest["id"]))
            if git.get("short"):
                print("  git {}{}   compare with:  python run_archive/runs.py diff {} latest\n"
                      .format(git["short"],
                              " (dirty)" if git.get("dirty") else "",
                              manifest["id"]))
            else:
                print("")
        except Exception as exc:                             # noqa: BLE001
            print("WARNING: could not archive this run ({}: {}). "
                  "Results were still written.\n"
                  .format(type(exc).__name__, exc))

    report(par, results, summary)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:                              # noqa: BLE001
        print("\nERROR: {}: {}".format(type(exc).__name__, exc))
        sys.exit(1)
