"""
My First Dispatch Model (MFDM)
==============================

A least-cost economic dispatch model built with PuLP.

Sets
    PLANTS  power plants
    HOURS   hour-by-hour time steps
    FUELS   fuels

Parameters
    availability[p][t]  MW that plant p can supply in hour t. Thermal plants
                        are available at nameplate around the clock; wind and
                        solar are nameplate scaled by an hourly capacity
                        factor read from profiles.csv.
    marginal_cost[p]    fuel_price / efficiency + VOM   ($/MWh)
    demand[t]           MWh required in hour t

Decision variable
    gen[p][t]           MWh generated by plant p in hour t

Objective
    minimise sum over p, t of marginal_cost[p] * gen[p][t]

Constraints
    energy balance  sum over p of gen[p][t] == demand[t]
    capacity        gen[p][t] <= availability[p][t]

After solving, the hourly market clearing price is taken as the marginal cost
of the most expensive plant running in that hour, and is cross-checked against
the dual (shadow price) of the energy balance constraint.

Outputs two CSVs, dispatch_results.csv and plant_summary.csv. Run dashboard.py
afterwards to explore the results interactively.
"""

from pathlib import Path
import argparse
import sys
import time

import pandas as pd
import pulp

import runstore


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

DATA_DIR = Path(__file__).resolve().parent

PLANTS_FILE = DATA_DIR / "plants.csv"
FUEL_FILE = DATA_DIR / "fuel.csv"
DEMAND_FILE = DATA_DIR / "demand.csv"
PROFILE_FILE = DATA_DIR / "profiles.csv"


# Generation below this is treated as "not running" when finding the marginal
# plant, so that solver round-off does not set the price.
TOL = 1e-6

# Technologies whose output is limited by an hourly resource profile rather
# than being available at nameplate around the clock. The value is the token
# looked for in the profiles.csv column headers.
PROFILE_TECHNOLOGIES = {
    "Wind": "wind",
    "Solar": "solar",
}


# --------------------------------------------------------------------------
# Step 1 - load data
# --------------------------------------------------------------------------

def load_data():
    """Read the four input CSVs and return them as DataFrames."""
    for path in (PLANTS_FILE, FUEL_FILE, DEMAND_FILE, PROFILE_FILE):
        if not path.exists():
            raise FileNotFoundError("Could not find input file: {}".format(path))

    # keep_default_na=False so that Solar's fuel of "None" stays the literal
    # string "None" rather than becoming NaN.
    plants = pd.read_csv(PLANTS_FILE, keep_default_na=False)
    fuel = pd.read_csv(FUEL_FILE)
    demand = pd.read_csv(DEMAND_FILE)

    # profiles.csv has two header rows: a region row (",FRA,FRA") and a
    # series row ("hours,wind (won),solar (solEB)"). Read both, then flatten
    # to single names of the form "FRA wind (won)", keeping the region so
    # multi-region files stay unambiguous.
    profile = pd.read_csv(PROFILE_FILE, header=[0, 1])
    flat = []
    for region, series in profile.columns:
        region = "" if str(region).startswith("Unnamed") else str(region).strip()
        series = str(series).strip()
        flat.append("{} {}".format(region, series).strip())
    profile.columns = flat

    # Tidy up stray whitespace in the text columns.
    for df in (plants, fuel, demand):
        df.columns = [c.strip() for c in df.columns]
    for col in ("Plant", "Technology", "Fuel"):
        plants[col] = plants[col].astype(str).str.strip()
    fuel["Technology"] = fuel["Technology"].astype(str).str.strip()

    return plants, fuel, demand, profile


# --------------------------------------------------------------------------
# Steps 2 and 3 - sets and parameters
# --------------------------------------------------------------------------

def build_parameters(plants, fuel, demand, profile):
    """Turn the raw DataFrames into the sets and parameter dictionaries."""

    # --- sets ---
    PLANTS = list(plants["Plant"])
    HOURS = [int(h) for h in demand["Hour"]]

    # --- fuel prices ---
    # fuel.csv labels its key column "Technology" but the values (Coal, Gas,
    # Diesel, Uranium, Hydrogen) are fuels, so we join on the plants' Fuel
    # column. Anything not listed - notably Solar's fuel of "None" - is free.
    fuel_price = dict(zip(fuel["Technology"], fuel["Fuel Price ($/MWhTh)"].astype(float)))

    def price_of(fuel_name):
        if fuel_name is None:
            return 0.0
        if str(fuel_name).strip().lower() in ("none", "nan", ""):
            return 0.0
        if fuel_name not in fuel_price:
            print("  note: no fuel price listed for '{}', treating as $0/MWhTh".format(fuel_name))
            return 0.0
        return fuel_price[fuel_name]

    # --- per plant parameters ---
    capacity = {}
    efficiency = {}
    vom = {}
    technology = {}
    plant_fuel = {}
    marginal_cost = {}

    for _, row in plants.iterrows():
        p = row["Plant"]
        capacity[p] = float(row["Capacity (MW)"])
        efficiency[p] = float(row["Efficiency (MWh/MWhTh)"])
        vom[p] = float(row["VOM ($/MWh)"])
        technology[p] = row["Technology"]
        plant_fuel[p] = row["Fuel"]

        if efficiency[p] <= 0:
            raise ValueError("Plant {} has a non-positive efficiency".format(p))

        # marginal cost = fuel cost / efficiency + variable O&M
        marginal_cost[p] = price_of(row["Fuel"]) / efficiency[p] + vom[p]

    # --- availability: nameplate capacity, scaled by an hourly resource
    # profile for the technologies that have one ---
    profile_factors = build_profile_factors(profile, technology, HOURS)
    availability = {}
    for p in PLANTS:
        factors = profile_factors.get(p)
        if factors is None:
            # Thermal plant: assumed available at nameplate around the clock.
            availability[p] = {t: capacity[p] for t in HOURS}
        else:
            availability[p] = {t: capacity[p] * factors[t] for t in HOURS}

    # --- demand ---
    demand_col = [c for c in demand.columns if c.lower().startswith("demand")][0]
    demand_by_hour = dict(zip(HOURS, demand[demand_col].astype(float)))

    return {
        "PLANTS": PLANTS,
        "HOURS": HOURS,
        "capacity": capacity,
        "efficiency": efficiency,
        "vom": vom,
        "technology": technology,
        "plant_fuel": plant_fuel,
        "marginal_cost": marginal_cost,
        "availability": availability,
        "profiled": set(profile_factors),
        "demand": demand_by_hour,
    }


def build_profile_factors(profile, technology, HOURS):
    """Map each profiled plant to its hourly capacity factor.

    Returns {plant: {hour: factor}} containing only the plants whose
    technology has a matching column in profiles.csv. Plants absent from the
    result are treated as available at nameplate in every hour.
    """
    hour_col = profile.columns[0]
    available_hours = set(int(h) for h in profile[hour_col])

    missing = [t for t in HOURS if t not in available_hours]
    if missing:
        raise ValueError(
            "profiles.csv is missing {} of the {} hours in demand.csv "
            "(first missing: hour {}).".format(len(missing), len(HOURS), missing[0]))

    # Restrict to the modelled hours. profiles.csv covers a full year (8784
    # hours) while demand.csv may cover only part of it.
    idx = profile[hour_col].astype(int)
    sub = profile.set_index(idx).loc[HOURS]

    factors = {}
    for plant, tech in technology.items():
        token = PROFILE_TECHNOLOGIES.get(tech)
        if token is None:
            continue

        matches = [c for c in profile.columns
                   if c is not hour_col and token in c.lower()]
        if not matches:
            print("  note: technology '{}' has no profile column in profiles.csv, "
                  "treating {} as always available".format(tech, plant))
            continue
        if len(matches) > 1:
            raise ValueError(
                "Technology '{}' matches more than one profile column: {}. "
                "Column names must be unambiguous.".format(tech, matches))

        series = sub[matches[0]].astype(float)
        lo, hi = float(series.min()), float(series.max())
        if lo < -TOL or hi > 1.0 + TOL:
            raise ValueError(
                "Profile column '{}' has values outside 0 to 1 (min {:.4f}, "
                "max {:.4f}). Expected capacity factors.".format(matches[0], lo, hi))

        factors[plant] = {t: float(v) for t, v in zip(HOURS, series.values)}

    return factors


def check_demand(par):
    """Flag suspicious demand values. These are not fatal, but a zero in the
    middle of an otherwise continuous series is usually a data entry slip
    rather than a real hour of no demand."""
    zeros = [t for t in par["HOURS"] if par["demand"][t] <= 0.0]
    if zeros:
        shown = ", ".join(str(t) for t in zeros[:10])
        more = " and {} more".format(len(zeros) - 10) if len(zeros) > 10 else ""
        print("  WARNING: demand is zero or negative in {} hour(s): {}{}."
              .format(len(zeros), shown, more))
        print("           Check demand.csv. The model will dispatch nothing "
              "in those hours.\n")


def check_feasibility(par):
    """Warn early if demand can never be met, which gives a clearer message
    than an 'Infeasible' status from the solver."""
    short = []
    for t in par["HOURS"]:
        total = sum(par["availability"][p][t] for p in par["PLANTS"])
        if total < par["demand"][t] - TOL:
            short.append((t, par["demand"][t], total))
    if short:
        t, d, a = short[0]
        worst = max(short, key=lambda r: r[1] - r[2])
        raise ValueError(
            "Demand exceeds available capacity in {} of {} hour(s). "
            "First is hour {}: demand {:.2f} MWh vs {:.2f} MW available. "
            "Worst is hour {}, short by {:.2f} MW. "
            "Note that wind and solar are limited by their hourly profiles, "
            "so firm capacity is what matters at peak."
            .format(len(short), len(par["HOURS"]), t, d, a,
                    worst[0], worst[1] - worst[2])
        )


# --------------------------------------------------------------------------
# Steps 4 to 7 - build and solve the LP
# --------------------------------------------------------------------------

def build_and_solve(par):
    """Build the dispatch LP, solve it, and return the model and variables."""

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]

    prob = pulp.LpProblem("Economic_Dispatch", pulp.LpMinimize)

    # --- Step 4: decision variables ---
    gen = pulp.LpVariable.dicts("gen", (PLANTS, HOURS), lowBound=0, cat="Continuous")

    # --- Step 5: objective, total production cost ---
    prob += (
        pulp.lpSum(par["marginal_cost"][p] * gen[p][t] for p in PLANTS for t in HOURS),
        "Total_Production_Cost",
    )

    # --- Step 6a: energy balance, one per hour ---
    # Named so the dual (shadow price) can be pulled out after solving.
    for t in HOURS:
        prob += (
            pulp.lpSum(gen[p][t] for p in PLANTS) == par["demand"][t],
            "balance_{}".format(t),
        )

    # --- Step 6b: capacity, one per plant per hour ---
    for p in PLANTS:
        for t in HOURS:
            prob += (
                gen[p][t] <= par["availability"][p][t],
                "cap_{}_{}".format(p.replace(" ", "_"), t),
            )

    # --- Step 7: solve ---
    print("Solving: {} variables, {} constraints ...".format(
        len(PLANTS) * len(HOURS), len(prob.constraints)))
    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    status = pulp.LpStatus[prob.status]
    if status != "Optimal":
        raise RuntimeError(
            "Solver did not reach an optimal solution (status: {}). "
            "Check that capacity covers demand in every hour.".format(status)
        )
    print("Solver status: {}\n".format(status))

    return prob, gen


# --------------------------------------------------------------------------
# Step 8 - results and clearing price
# --------------------------------------------------------------------------

def build_results(par, prob, gen):
    """Assemble the hourly results table, including the clearing price."""

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]
    mc = par["marginal_cost"]

    rows = []
    mismatches = 0

    for t in HOURS:
        row = {"Hour": t, "Demand (MWh)": par["demand"][t]}

        output = {p: (gen[p][t].value() or 0.0) for p in PLANTS}
        for p in PLANTS:
            row["{} (MWh)".format(p)] = output[p]

        # Availability is written out as well as generation, because a
        # profiled plant sitting at its resource limit is at capacity even
        # though it is far below nameplate. Anything reading these results
        # needs the hourly limit to tell "maxed out" from "part loaded".
        for p in PLANTS:
            row["{} Available (MWh)".format(p)] = par["availability"][p][t]

        # Clearing price, method 1: merit order. The most expensive plant
        # actually generating sets the price.
        running = [p for p in PLANTS if output[p] > TOL]
        price_merit = max((mc[p] for p in running), default=0.0)

        # Clearing price, method 2: the dual of the energy balance constraint.
        constraint = prob.constraints.get("balance_{}".format(t))
        price_dual = constraint.pi if constraint is not None and constraint.pi is not None else None

        # These agree except in degenerate hours where a plant sits exactly on
        # its cap. Report the merit-order value as briefed, but flag any gap.
        if price_dual is not None and abs(price_dual - price_merit) > 1e-4:
            mismatches += 1

        row["Clearing Price ($/MWh)"] = price_merit
        row["Shadow Price ($/MWh)"] = price_dual
        row["Production Cost ($)"] = sum(mc[p] * output[p] for p in PLANTS)
        row["Market Cost ($)"] = price_merit * par["demand"][t]

        # Curtailment: profiled renewable energy that was available but not
        # taken, because demand was already met by cheaper or equal output.
        curtailed = 0.0
        for p in par["profiled"]:
            curtailed += max(0.0, par["availability"][p][t] - output[p])
        row["Curtailment (MWh)"] = curtailed

        rows.append(row)

    if mismatches:
        print("  note: merit-order and shadow prices differ in {} of {} hours "
              "(expected in degenerate hours where a plant sits exactly on its cap)\n"
              .format(mismatches, len(HOURS)))

    return pd.DataFrame(rows)


def build_summary(par, results):
    """Per-plant totals: energy, capacity factor, hours running, cost."""

    n_hours = len(par["HOURS"])
    rows = []

    for p in par["PLANTS"]:
        series = results["{} (MWh)".format(p)]
        total = series.sum()
        max_possible = par["capacity"][p] * n_hours

        # Energy the plant could have produced given its resource. For a
        # thermal plant this is just nameplate around the clock; for wind and
        # solar it is limited by the hourly profile.
        is_profiled = p in par["profiled"]
        available = sum(par["availability"][p][t] for t in par["HOURS"])

        # Curtailment only means something for a profiled plant: energy the
        # resource offered but the dispatch did not take. Idle thermal
        # capacity is not curtailment, it is simply not being called on.
        curtailed = max(0.0, available - total) if is_profiled else 0.0

        # A plant sets the price in an hour when it is running and its
        # marginal cost equals the clearing price.
        is_running = series > TOL
        is_marginal = (results["Clearing Price ($/MWh)"] - par["marginal_cost"][p]).abs() < 1e-6
        hours_setting_price = int((is_running & is_marginal).sum())

        rows.append({
            "Plant": p,
            "Technology": par["technology"][p],
            "Fuel": par["plant_fuel"][p],
            "Capacity (MW)": par["capacity"][p],
            "Profiled": is_profiled,
            "Marginal Cost ($/MWh)": par["marginal_cost"][p],
            "Total Generation (MWh)": total,
            "Available Energy (MWh)": available,
            "Curtailed (MWh)": curtailed,
            "Curtailment (%)": (100.0 * curtailed / available
                                if is_profiled and available > 0 else 0.0),
            "Share of Demand (%)": 100.0 * total / results["Demand (MWh)"].sum(),
            "Capacity Factor (%)": 100.0 * total / max_possible if max_possible else 0.0,
            "Availability Factor (%)": (100.0 * available / max_possible
                                        if max_possible else 0.0),
            "Hours Running": int(is_running.sum()),
            "Hours Setting Price": hours_setting_price,
            "Production Cost ($)": total * par["marginal_cost"][p],
        })

    return pd.DataFrame(rows).sort_values("Marginal Cost ($/MWh)").reset_index(drop=True)


# --------------------------------------------------------------------------
# Step 9 - reporting
# --------------------------------------------------------------------------

def report(par, results, summary):
    print("-" * 68)
    print("MARGINAL COSTS  (fuel price / efficiency + VOM)")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:<10} {:>7.1f} MW   ${:>7.2f}/MWh{}"
              .format(r["Plant"], str(r["Technology"]), r["Capacity (MW)"],
                      r["Marginal Cost ($/MWh)"],
                      "   (profiled)" if r["Profiled"] else ""))

    print("\n" + "-" * 68)
    print("DISPATCH SUMMARY")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:>12,.1f} MWh   CF {:>5.1f}%   running {:>4} h   sets price {:>4} h"
              .format(r["Plant"], r["Total Generation (MWh)"], r["Capacity Factor (%)"],
                      r["Hours Running"], r["Hours Setting Price"]))

    profiled = summary[summary["Profiled"]]
    if not profiled.empty:
        print("\n" + "-" * 68)
        print("RENEWABLE RESOURCE  (capacity factor is after curtailment)")
        print("-" * 68)
        for _, r in profiled.iterrows():
            print("  {:<10} resource {:>5.1f}%   used {:>5.1f}%   "
                  "available {:>10,.1f} MWh   curtailed {:>8,.1f} MWh ({:.1f}%)"
                  .format(r["Plant"], r["Availability Factor (%)"],
                          r["Capacity Factor (%)"], r["Available Energy (MWh)"],
                          r["Curtailed (MWh)"], r["Curtailment (%)"]))

    total_demand = results["Demand (MWh)"].sum()
    total_gen = summary["Total Generation (MWh)"].sum()
    prod_cost = results["Production Cost ($)"].sum()
    market_cost = results["Market Cost ($)"].sum()

    print("\n" + "-" * 68)
    print("TOTALS OVER {} HOURS".format(len(results)))
    print("-" * 68)
    print("  Energy served              {:>16,.1f} MWh".format(total_demand))
    print("  Energy generated           {:>16,.1f} MWh".format(total_gen))
    print("  Total production cost      {:>16,.2f} $      (the LP objective)".format(prod_cost))
    print("  Average production cost    {:>16,.2f} $/MWh".format(prod_cost / total_demand))
    print("  Total market cost          {:>16,.2f} $      (clearing price x demand)"
          .format(market_cost))
    print("  Time-weighted avg price    {:>16,.2f} $/MWh"
          .format(results["Clearing Price ($/MWh)"].mean()))
    print("  Load-weighted avg price    {:>16,.2f} $/MWh".format(market_cost / total_demand))
    print("  Producer surplus           {:>16,.2f} $      (market - production)"
          .format(market_cost - prod_cost))

    total_curtailed = results["Curtailment (MWh)"].sum()
    if par["profiled"]:
        avail = summary.loc[summary["Profiled"], "Available Energy (MWh)"].sum()
        used = summary.loc[summary["Profiled"], "Total Generation (MWh)"].sum()
        print("  Renewable energy used      {:>16,.1f} MWh   ({:.1f}% of demand)"
              .format(used, 100.0 * used / total_demand if total_demand else 0.0))
        print("  Renewable curtailed        {:>16,.1f} MWh   ({:.1f}% of available)"
              .format(total_curtailed,
                      100.0 * total_curtailed / avail if avail else 0.0))

    # Energy balance check.
    gap = abs(total_gen - total_demand)
    print("\n  Energy balance check: |generation - demand| = {:.6f} MWh {}"
          .format(gap, "OK" if gap < 1e-3 else "<-- PROBLEM"))

    print("\n  Hours at each clearing price:")
    for price, count in sorted(results["Clearing Price ($/MWh)"].value_counts().items()):
        setter = [p for p in par["PLANTS"] if abs(par["marginal_cost"][p] - price) < 1e-6]
        who = setter[0] if setter else "n/a"
        print("    ${:>7.2f}/MWh   {:>4} h  ({:>5.1f}%)   set by {}"
              .format(price, count, 100.0 * count / len(results), who))
    print("")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Least-cost economic dispatch model.")
    parser.add_argument("--label", default=None,
                        help="short name for this run, used in the archive id")
    parser.add_argument("--notes", default=None,
                        help="longer description stored with the run")
    parser.add_argument("--no-archive", action="store_true",
                        help="solve and write results without archiving the run")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    print("\n" + "=" * 68)
    print("MY FIRST DISPATCH MODEL")
    print("=" * 68 + "\n")

    plants, fuel, demand, profile = load_data()
    print("Loaded {} plants, {} fuels, {} hours, {} profile rows.\n"
          .format(len(plants), len(fuel), len(demand), len(profile)))

    par = build_parameters(plants, fuel, demand, profile)
    if par["profiled"]:
        print("  profiled technologies: {}\n".format(
            ", ".join("{} ({})".format(p, par["technology"][p])
                      for p in sorted(par["profiled"]))))
    check_demand(par)
    check_feasibility(par)

    started = time.time()
    prob, gen = build_and_solve(par)
    solve_seconds = round(time.time() - started, 3)

    results = build_results(par, prob, gen)
    summary = build_summary(par, results)

    results_path = DATA_DIR / "dispatch_results.csv"
    summary_path = DATA_DIR / "plant_summary.csv"
    results.round(6).to_csv(results_path, index=False)
    summary.round(6).to_csv(summary_path, index=False)
    print("Results written:\n  {}\n  {}\n".format(results_path, summary_path))

    # Archive the run so it can be compared or restored later. A failure here
    # must not lose the results, which are already safely on disk.
    if not args.no_archive:
        try:
            manifest = runstore.archive_run(
                label=args.label, notes=args.notes,
                solver_status=pulp.LpStatus[prob.status], seconds=solve_seconds)
            git = manifest["git"]
            print("Archived as run: {}".format(manifest["id"]))
            if git.get("short"):
                print("  git {}{}   compare with:  python runs.py diff {} latest\n"
                      .format(git["short"],
                              " (dirty)" if git.get("dirty") else "",
                              manifest["id"]))
            else:
                print("")
        except Exception as exc:                             # noqa: BLE001
            print("WARNING: could not archive this run ({}: {}). "
                  "Results were still written.\n"
                  .format(type(exc).__name__, exc))

    report(par, results, summary)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:                              # noqa: BLE001
        print("\nERROR: {}: {}".format(type(exc).__name__, exc))
        sys.exit(1)
