"""
My First Dispatch Model (MFDM)
==============================

A least-cost economic dispatch model built with PuLP.

Sets
    PLANTS  power plants
    HOURS   hour-by-hour time steps
    FUELS   fuels

Parameters
    availability[p][t]  MW that plant p can supply in hour t
    marginal_cost[p]    fuel_price / efficiency + VOM   ($/MWh)
    demand[t]           MWh required in hour t

Decision variable
    gen[p][t]           MWh generated by plant p in hour t

Objective
    minimise sum over p, t of marginal_cost[p] * gen[p][t]

Constraints
    energy balance  sum over p of gen[p][t] == demand[t]
    capacity        gen[p][t] <= availability[p][t]

After solving, the hourly market clearing price is taken as the marginal cost
of the most expensive plant running in that hour, and is cross-checked against
the dual (shadow price) of the energy balance constraint.
"""

from pathlib import Path
import sys

import pandas as pd
import pulp

import matplotlib
matplotlib.use("Agg")          # no GUI window; must be set before pyplot
import matplotlib.pyplot as plt


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

DATA_DIR = Path(__file__).resolve().parent

PLANTS_FILE = DATA_DIR / "plants.csv"
FUEL_FILE = DATA_DIR / "fuel.csv"
DEMAND_FILE = DATA_DIR / "demand.csv"

# Generation below this is treated as "not running" when finding the marginal
# plant, so that solver round-off does not set the price.
TOL = 1e-6

# Consistent colour per plant technology across every chart.
TECH_COLOURS = {
    "Solar": "#F5B301",
    "Wind": "#4CAF50",
    "Coal": "#4A4A4A",
    "Gas": "#1F77B4",
    "Diesel": "#8B4513",
    "Nuclear": "#9467BD",
    "Hydrogen": "#17BECF",
}
FALLBACK_COLOURS = ["#E377C2", "#7F7F7F", "#BCBD22", "#2CA02C", "#D62728"]

# Hours shown in the zoomed-in dispatch plot.
ZOOM_HOURS = 168        # one week


# --------------------------------------------------------------------------
# Step 1 - load data
# --------------------------------------------------------------------------

def load_data():
    """Read the three input CSVs and return them as DataFrames."""
    for path in (PLANTS_FILE, FUEL_FILE, DEMAND_FILE):
        if not path.exists():
            raise FileNotFoundError("Could not find input file: {}".format(path))

    plants = pd.read_csv(PLANTS_FILE)
    fuel = pd.read_csv(FUEL_FILE)
    demand = pd.read_csv(DEMAND_FILE)

    # Tidy up stray whitespace in the text columns.
    for df in (plants, fuel, demand):
        df.columns = [c.strip() for c in df.columns]
    for col in ("Plant", "Technology", "Fuel"):
        plants[col] = plants[col].astype(str).str.strip()
    fuel["Technology"] = fuel["Technology"].astype(str).str.strip()

    return plants, fuel, demand


# --------------------------------------------------------------------------
# Steps 2 and 3 - sets and parameters
# --------------------------------------------------------------------------

def build_parameters(plants, fuel, demand):
    """Turn the raw DataFrames into the sets and parameter dictionaries."""

    # --- sets ---
    PLANTS = list(plants["Plant"])
    HOURS = [int(h) for h in demand["Hour"]]

    # --- fuel prices ---
    # fuel.csv labels its key column "Technology" but the values (Coal, Gas,
    # Diesel, Uranium, Hydrogen) are fuels, so we join on the plants' Fuel
    # column. Anything not listed - notably Solar's fuel of "None" - is free.
    fuel_price = dict(zip(fuel["Technology"], fuel["Fuel Price ($/MWhTh)"].astype(float)))

    def price_of(fuel_name):
        if fuel_name is None:
            return 0.0
        if str(fuel_name).strip().lower() in ("none", "nan", ""):
            return 0.0
        if fuel_name not in fuel_price:
            print("  note: no fuel price listed for '{}', treating as $0/MWhTh".format(fuel_name))
            return 0.0
        return fuel_price[fuel_name]

    # --- per plant parameters ---
    capacity = {}
    efficiency = {}
    vom = {}
    technology = {}
    plant_fuel = {}
    marginal_cost = {}

    for _, row in plants.iterrows():
        p = row["Plant"]
        capacity[p] = float(row["Capacity (MW)"])
        efficiency[p] = float(row["Efficiency (MWh/MWhTh)"])
        vom[p] = float(row["VOM ($/MWh)"])
        technology[p] = row["Technology"]
        plant_fuel[p] = row["Fuel"]

        if efficiency[p] <= 0:
            raise ValueError("Plant {} has a non-positive efficiency".format(p))

        # marginal cost = fuel cost / efficiency + variable O&M
        marginal_cost[p] = price_of(row["Fuel"]) / efficiency[p] + vom[p]

    # --- availability: flat at nameplate capacity in every hour ---
    # Stored as a full plant-by-hour table so a real hourly profile can be
    # dropped in later without changing any of the constraints below.
    availability = {p: {t: capacity[p] for t in HOURS} for p in PLANTS}

    # --- demand ---
    demand_col = [c for c in demand.columns if c.lower().startswith("demand")][0]
    demand_by_hour = dict(zip(HOURS, demand[demand_col].astype(float)))

    return {
        "PLANTS": PLANTS,
        "HOURS": HOURS,
        "capacity": capacity,
        "efficiency": efficiency,
        "vom": vom,
        "technology": technology,
        "plant_fuel": plant_fuel,
        "marginal_cost": marginal_cost,
        "availability": availability,
        "demand": demand_by_hour,
    }


def check_feasibility(par):
    """Warn early if demand can never be met, which gives a clearer message
    than an 'Infeasible' status from the solver."""
    short = []
    for t in par["HOURS"]:
        total = sum(par["availability"][p][t] for p in par["PLANTS"])
        if total < par["demand"][t] - TOL:
            short.append((t, par["demand"][t], total))
    if short:
        t, d, a = short[0]
        raise ValueError(
            "Demand exceeds available capacity in {} hour(s). "
            "First is hour {}: demand {:.2f} MWh vs {:.2f} MW available."
            .format(len(short), t, d, a)
        )


# --------------------------------------------------------------------------
# Steps 4 to 7 - build and solve the LP
# --------------------------------------------------------------------------

def build_and_solve(par):
    """Build the dispatch LP, solve it, and return the model and variables."""

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]

    prob = pulp.LpProblem("Economic_Dispatch", pulp.LpMinimize)

    # --- Step 4: decision variables ---
    gen = pulp.LpVariable.dicts("gen", (PLANTS, HOURS), lowBound=0, cat="Continuous")

    # --- Step 5: objective, total production cost ---
    prob += (
        pulp.lpSum(par["marginal_cost"][p] * gen[p][t] for p in PLANTS for t in HOURS),
        "Total_Production_Cost",
    )

    # --- Step 6a: energy balance, one per hour ---
    # Named so the dual (shadow price) can be pulled out after solving.
    for t in HOURS:
        prob += (
            pulp.lpSum(gen[p][t] for p in PLANTS) == par["demand"][t],
            "balance_{}".format(t),
        )

    # --- Step 6b: capacity, one per plant per hour ---
    for p in PLANTS:
        for t in HOURS:
            prob += (
                gen[p][t] <= par["availability"][p][t],
                "cap_{}_{}".format(p.replace(" ", "_"), t),
            )

    # --- Step 7: solve ---
    print("Solving: {} variables, {} constraints ...".format(
        len(PLANTS) * len(HOURS), len(prob.constraints)))
    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    status = pulp.LpStatus[prob.status]
    if status != "Optimal":
        raise RuntimeError(
            "Solver did not reach an optimal solution (status: {}). "
            "Check that capacity covers demand in every hour.".format(status)
        )
    print("Solver status: {}\n".format(status))

    return prob, gen


# --------------------------------------------------------------------------
# Step 8 - results and clearing price
# --------------------------------------------------------------------------

def build_results(par, prob, gen):
    """Assemble the hourly results table, including the clearing price."""

    PLANTS, HOURS = par["PLANTS"], par["HOURS"]
    mc = par["marginal_cost"]

    rows = []
    mismatches = 0

    for t in HOURS:
        row = {"Hour": t, "Demand (MWh)": par["demand"][t]}

        output = {p: (gen[p][t].value() or 0.0) for p in PLANTS}
        for p in PLANTS:
            row["{} (MWh)".format(p)] = output[p]

        # Clearing price, method 1: merit order. The most expensive plant
        # actually generating sets the price.
        running = [p for p in PLANTS if output[p] > TOL]
        price_merit = max((mc[p] for p in running), default=0.0)

        # Clearing price, method 2: the dual of the energy balance constraint.
        constraint = prob.constraints.get("balance_{}".format(t))
        price_dual = constraint.pi if constraint is not None and constraint.pi is not None else None

        # These agree except in degenerate hours where a plant sits exactly on
        # its cap. Report the merit-order value as briefed, but flag any gap.
        if price_dual is not None and abs(price_dual - price_merit) > 1e-4:
            mismatches += 1

        row["Clearing Price ($/MWh)"] = price_merit
        row["Shadow Price ($/MWh)"] = price_dual
        row["Production Cost ($)"] = sum(mc[p] * output[p] for p in PLANTS)
        row["Market Cost ($)"] = price_merit * par["demand"][t]
        rows.append(row)

    if mismatches:
        print("  note: merit-order and shadow prices differ in {} of {} hours "
              "(expected in degenerate hours where a plant sits exactly on its cap)\n"
              .format(mismatches, len(HOURS)))

    return pd.DataFrame(rows)


def build_summary(par, results):
    """Per-plant totals: energy, capacity factor, hours running, cost."""

    n_hours = len(par["HOURS"])
    rows = []

    for p in par["PLANTS"]:
        series = results["{} (MWh)".format(p)]
        total = series.sum()
        max_possible = par["capacity"][p] * n_hours

        # A plant sets the price in an hour when it is running and its
        # marginal cost equals the clearing price.
        is_running = series > TOL
        is_marginal = (results["Clearing Price ($/MWh)"] - par["marginal_cost"][p]).abs() < 1e-6
        hours_setting_price = int((is_running & is_marginal).sum())

        rows.append({
            "Plant": p,
            "Technology": par["technology"][p],
            "Fuel": par["plant_fuel"][p],
            "Capacity (MW)": par["capacity"][p],
            "Marginal Cost ($/MWh)": par["marginal_cost"][p],
            "Total Generation (MWh)": total,
            "Share of Demand (%)": 100.0 * total / results["Demand (MWh)"].sum(),
            "Capacity Factor (%)": 100.0 * total / max_possible if max_possible else 0.0,
            "Hours Running": int(is_running.sum()),
            "Hours Setting Price": hours_setting_price,
            "Production Cost ($)": total * par["marginal_cost"][p],
        })

    return pd.DataFrame(rows).sort_values("Marginal Cost ($/MWh)").reset_index(drop=True)


# --------------------------------------------------------------------------
# Step 10 - plots
# --------------------------------------------------------------------------

def colour_for(par, plant, index):
    tech = par["technology"].get(plant, "")
    if tech in TECH_COLOURS:
        return TECH_COLOURS[tech]
    return FALLBACK_COLOURS[index % len(FALLBACK_COLOURS)]


def plot_dispatch_stack(par, results, path, hours=None, title=None):
    """Stacked generation with demand overlaid. If the dashed demand line does
    not sit exactly on top of the stack, the energy balance is broken."""

    df = results if hours is None else results.head(hours)

    # Stack cheapest first so the picture reads as a merit order.
    order = sorted(par["PLANTS"], key=lambda p: par["marginal_cost"][p])
    series = [df["{} (MWh)".format(p)].values for p in order]
    colours = [colour_for(par, p, i) for i, p in enumerate(order)]
    labels = ["{} ({}) ${:.2f}/MWh".format(p, par["technology"][p], par["marginal_cost"][p])
              for p in order]

    fig, ax = plt.subplots(figsize=(14, 6))
    ax.stackplot(df["Hour"].values, *series, labels=labels, colors=colours, alpha=0.9)
    ax.plot(df["Hour"].values, df["Demand (MWh)"].values,
            color="black", linestyle="--", linewidth=1.4, label="Demand")

    ax.set_xlabel("Hour")
    ax.set_ylabel("Generation (MWh)")
    ax.set_title(title or "Dispatch by plant")
    ax.legend(loc="upper left", fontsize=8, ncol=2)
    ax.margins(x=0)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_price(par, results, path):
    """Price is piecewise constant, so draw it as a step line. Expect only the
    distinct marginal cost values to appear."""

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.plot(results["Hour"].values, results["Clearing Price ($/MWh)"].values,
            drawstyle="steps-post", color="#C0392B", linewidth=1.2)

    for i, p in enumerate(sorted(par["PLANTS"], key=lambda x: par["marginal_cost"][x])):
        ax.axhline(par["marginal_cost"][p], color=colour_for(par, p, i),
                   linestyle=":", linewidth=1,
                   label="{} ${:.2f}/MWh".format(p, par["marginal_cost"][p]))

    ax.set_xlabel("Hour")
    ax.set_ylabel("Clearing price ($/MWh)")
    ax.set_title("Hourly market clearing price (marginal cost of the most expensive plant running)")
    ax.legend(loc="upper left", fontsize=8)
    ax.margins(x=0)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_price_duration(results, path):
    """Price sorted high to low: what share of the month each plant sets price."""

    prices = results["Clearing Price ($/MWh)"].sort_values(ascending=False).values
    pct = [100.0 * (i + 1) / len(prices) for i in range(len(prices))]

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(pct, prices, drawstyle="steps-post", color="#C0392B", linewidth=1.8)
    ax.fill_between(pct, prices, step="post", alpha=0.25, color="#C0392B")
    ax.set_xlabel("Percent of hours (%)")
    ax.set_ylabel("Clearing price ($/MWh)")
    ax.set_title("Price duration curve")
    ax.margins(x=0)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_load_duration(par, results, path):
    """Demand sorted high to low, with cumulative capacity lines. Where the
    curve crosses a line is where the marginal plant changes, so this should
    agree with the price duration curve."""

    loads = results["Demand (MWh)"].sort_values(ascending=False).values
    pct = [100.0 * (i + 1) / len(loads) for i in range(len(loads))]

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(pct, loads, color="black", linewidth=1.8, label="Demand")

    cumulative = 0.0
    for i, p in enumerate(sorted(par["PLANTS"], key=lambda x: par["marginal_cost"][x])):
        cumulative += par["capacity"][p]
        ax.axhline(cumulative, color=colour_for(par, p, i), linestyle="--", linewidth=1.2,
                   label="cum. capacity through {} = {:.0f} MW".format(p, cumulative))

    ax.set_xlabel("Percent of hours (%)")
    ax.set_ylabel("Demand (MWh)")
    ax.set_title("Load duration curve vs cumulative capacity")
    ax.legend(loc="upper right", fontsize=8)
    ax.margins(x=0)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def plot_energy_mix(par, summary, path):
    """Total energy per plant, labelled with capacity factor."""

    fig, ax = plt.subplots(figsize=(9, 5.5))
    colours = [colour_for(par, p, i) for i, p in enumerate(summary["Plant"])]
    bars = ax.bar(summary["Plant"], summary["Total Generation (MWh)"], color=colours)

    top = summary["Total Generation (MWh)"].max()
    for bar, cf, share in zip(bars, summary["Capacity Factor (%)"], summary["Share of Demand (%)"]):
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + top * 0.015,
                "CF {:.1f}%\n{:.1f}% of demand".format(cf, share),
                ha="center", va="bottom", fontsize=9)

    ax.set_ylabel("Total generation (MWh)")
    ax.set_title("Energy mix over the modelled period")
    ax.set_ylim(0, top * 1.20 if top else 1)
    ax.grid(alpha=0.3, axis="y")
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def make_plots(par, results, summary, out_dir):
    """Write all PNGs. Never let a plotting failure lose the CSV results."""
    try:
        plot_dispatch_stack(par, results, out_dir / "plot_dispatch_stack.png",
                            title="Dispatch by plant - all {} hours".format(len(results)))
        n = min(ZOOM_HOURS, len(results))
        plot_dispatch_stack(par, results, out_dir / "plot_dispatch_week.png",
                            hours=n, title="Dispatch by plant - first {} hours".format(n))
        plot_price(par, results, out_dir / "plot_price.png")
        plot_price_duration(results, out_dir / "plot_price_duration.png")
        plot_load_duration(par, results, out_dir / "plot_load_duration.png")
        plot_energy_mix(par, summary, out_dir / "plot_energy_mix.png")

        print("Plots written:")
        for name in ("plot_dispatch_stack.png", "plot_dispatch_week.png", "plot_price.png",
                     "plot_price_duration.png", "plot_load_duration.png", "plot_energy_mix.png"):
            print("  {}".format(out_dir / name))
        print("")
    except Exception as exc:                              # noqa: BLE001
        print("WARNING: plotting failed ({}: {}). CSV results were still written.\n"
              .format(type(exc).__name__, exc))


# --------------------------------------------------------------------------
# Step 9 - reporting
# --------------------------------------------------------------------------

def report(par, results, summary):
    print("-" * 68)
    print("MARGINAL COSTS  (fuel price / efficiency + VOM)")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:<10} {:>7.1f} MW   ${:>7.2f}/MWh"
              .format(r["Plant"], str(r["Technology"]), r["Capacity (MW)"],
                      r["Marginal Cost ($/MWh)"]))

    print("\n" + "-" * 68)
    print("DISPATCH SUMMARY")
    print("-" * 68)
    for _, r in summary.iterrows():
        print("  {:<10} {:>12,.1f} MWh   CF {:>5.1f}%   running {:>4} h   sets price {:>4} h"
              .format(r["Plant"], r["Total Generation (MWh)"], r["Capacity Factor (%)"],
                      r["Hours Running"], r["Hours Setting Price"]))

    total_demand = results["Demand (MWh)"].sum()
    total_gen = summary["Total Generation (MWh)"].sum()
    prod_cost = results["Production Cost ($)"].sum()
    market_cost = results["Market Cost ($)"].sum()

    print("\n" + "-" * 68)
    print("TOTALS OVER {} HOURS".format(len(results)))
    print("-" * 68)
    print("  Energy served              {:>16,.1f} MWh".format(total_demand))
    print("  Energy generated           {:>16,.1f} MWh".format(total_gen))
    print("  Total production cost      {:>16,.2f} $      (the LP objective)".format(prod_cost))
    print("  Average production cost    {:>16,.2f} $/MWh".format(prod_cost / total_demand))
    print("  Total market cost          {:>16,.2f} $      (clearing price x demand)"
          .format(market_cost))
    print("  Time-weighted avg price    {:>16,.2f} $/MWh"
          .format(results["Clearing Price ($/MWh)"].mean()))
    print("  Load-weighted avg price    {:>16,.2f} $/MWh".format(market_cost / total_demand))
    print("  Producer surplus           {:>16,.2f} $      (market - production)"
          .format(market_cost - prod_cost))

    # Energy balance check.
    gap = abs(total_gen - total_demand)
    print("\n  Energy balance check: |generation - demand| = {:.6f} MWh {}"
          .format(gap, "OK" if gap < 1e-3 else "<-- PROBLEM"))

    print("\n  Hours at each clearing price:")
    for price, count in sorted(results["Clearing Price ($/MWh)"].value_counts().items()):
        setter = [p for p in par["PLANTS"] if abs(par["marginal_cost"][p] - price) < 1e-6]
        who = setter[0] if setter else "n/a"
        print("    ${:>7.2f}/MWh   {:>4} h  ({:>5.1f}%)   set by {}"
              .format(price, count, 100.0 * count / len(results), who))
    print("")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    print("\n" + "=" * 68)
    print("MY FIRST DISPATCH MODEL")
    print("=" * 68 + "\n")

    plants, fuel, demand = load_data()
    print("Loaded {} plants, {} fuels, {} hours.\n"
          .format(len(plants), len(fuel), len(demand)))

    par = build_parameters(plants, fuel, demand)
    check_feasibility(par)

    prob, gen = build_and_solve(par)

    results = build_results(par, prob, gen)
    summary = build_summary(par, results)

    results_path = DATA_DIR / "dispatch_results.csv"
    summary_path = DATA_DIR / "plant_summary.csv"
    results.round(6).to_csv(results_path, index=False)
    summary.round(6).to_csv(summary_path, index=False)
    print("Results written:\n  {}\n  {}\n".format(results_path, summary_path))

    make_plots(par, results, summary, DATA_DIR)
    report(par, results, summary)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:                              # noqa: BLE001
        print("\nERROR: {}: {}".format(type(exc).__name__, exc))
        sys.exit(1)
